# Generated by Django 6.0.7 on 2026-07-08 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('employee_code', models.CharField(help_text='يتم توليده تلقائياً لو تركته فارغاً', max_length=20, verbose_name='الرقم الوظيفي')),
                ('first_name_ar', models.CharField(max_length=100, verbose_name='الاسم الأول بالعربي')),
                ('middle_name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم الأوسط بالعربي')),
                ('last_name_ar', models.CharField(max_length=100, verbose_name='الاسم الأخير بالعربي')),
                ('first_name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم الأول بالإنجليزي')),
                ('last_name_en', models.CharField(blank=True, max_length=100, null=True, verbose_name='الاسم الأخير بالإنجليزي')),
                ('national_id', models.CharField(max_length=20, verbose_name='الرقم القومي')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='النوع')),
                ('marital_status', models.CharField(choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], default='single', max_length=20, verbose_name='الحالة الاجتماعية')),
                ('religion', models.CharField(blank=True, choices=[('muslim', 'مسلم'), ('christian', 'مسيحي'), ('other', 'أخرى')], max_length=20, null=True, verbose_name='الديانة')),
                ('nationality', models.CharField(default='مصري', max_length=100, verbose_name='الجنسية')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/photos/', verbose_name='الصورة الشخصية')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الموبايل')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم موبايل آخر')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('hire_date', models.DateField(verbose_name='تاريخ التعيين')),
                ('contract_type', models.CharField(choices=[('permanent', 'دائم'), ('temporary', 'مؤقت'), ('training', 'تدريب'), ('freelance', 'حر'), ('part_time', 'دوام جزئي')], default='permanent', max_length=20, verbose_name='نوع العقد')),
                ('contract_end_date', models.DateField(blank=True, help_text='في حالة العقد المؤقت', null=True, verbose_name='تاريخ انتهاء العقد')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='الراتب الأساسي')),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم البنك')),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم الحساب')),
                ('iban', models.CharField(blank=True, max_length=50, null=True, verbose_name='IBAN')),
                ('insurance_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم التأميني')),
                ('insurance_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التأمين')),
                ('has_insurance', models.BooleanField(default=False, verbose_name='مؤمن عليه')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم جهة الاتصال')),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=50, null=True, verbose_name='صلة القرابة')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم جهة الاتصال')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('on_leave', 'في إجازة'), ('suspended', 'موقوف'), ('resigned', 'مستقيل'), ('terminated', 'مفصول'), ('retired', 'متقاعد')], default='active', max_length=20, verbose_name='الحالة')),
                ('termination_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الخدمة')),
                ('termination_reason', models.TextField(blank=True, null=True, verbose_name='سبب انتهاء الخدمة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_field_worker', models.BooleanField(default=False, help_text='يتم تتبع موقعه أثناء العمل', verbose_name='موظف ميداني')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='companies.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='companies.department', verbose_name='الإدارة')),
                ('direct_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to='employees.employee', verbose_name='المدير المباشر')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_profile', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
                'ordering': ['employee_code'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('document_type', models.CharField(choices=[('national_id', 'صورة البطاقة'), ('passport', 'جواز السفر'), ('contract', 'العقد'), ('certificate', 'شهادة'), ('cv', 'السيرة الذاتية'), ('medical', 'ملف طبي'), ('license', 'رخصة'), ('insurance', 'وثيقة تأمين'), ('other', 'أخرى')], max_length=30, verbose_name='نوع المستند')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('file', models.FileField(upload_to='employees/documents/', verbose_name='الملف')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإصدار')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الانتهاء')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'مستند',
                'verbose_name_plural': 'المستندات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('movement_type', models.CharField(choices=[('promotion', 'ترقية'), ('transfer', 'نقل'), ('salary_change', 'تعديل راتب'), ('department_change', 'تغيير إدارة'), ('branch_change', 'تغيير فرع'), ('job_title_change', 'تغيير مسمى'), ('contract_renewal', 'تجديد عقد'), ('warning', 'إنذار'), ('suspension', 'إيقاف'), ('resignation', 'استقالة'), ('termination', 'فصل'), ('return_from_leave', 'عودة من إجازة'), ('other', 'أخرى')], max_length=30, verbose_name='نوع الحركة')),
                ('movement_date', models.DateField(verbose_name='تاريخ الحركة')),
                ('old_value', models.CharField(blank=True, max_length=500, null=True, verbose_name='القيمة القديمة')),
                ('new_value', models.CharField(blank=True, max_length=500, null=True, verbose_name='القيمة الجديدة')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='السبب')),
                ('document', models.FileField(blank=True, null=True, upload_to='employees/movements/', verbose_name='مستند مرفق')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'حركة موظف',
                'verbose_name_plural': 'حركات الموظفين',
                'ordering': ['-movement_date'],
            },
        ),
        migrations.CreateModel(
            name='JobTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('name_ar', models.CharField(max_length=200, verbose_name='المسمى بالعربي')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='المسمى بالإنجليزي')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'مسمى وظيفي',
                'verbose_name_plural': 'المسميات الوظيفية',
                'ordering': ['name_ar'],
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='job_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.jobtitle', verbose_name='المسمى الوظيفي'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('company', 'employee_code'), ('company', 'national_id')},
        ),
    ]
