# Generated by Django 6.0.7 on 2026-07-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, help_text='يتم توليده تلقائياً لو تركته فارغاً', max_length=20, verbose_name='الرقم الوظيفي'),
        ),
    ]
