# Generated by Django 6.0.7 on 2026-07-10 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companyloginsettings_password_expiry_days'),
        ('employees', '0002_alter_employee_employee_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('deduction_type', models.CharField(choices=[('late', 'تأخير'), ('absence', 'غياب'), ('early_leave', 'انصراف مبكر'), ('violation', 'مخالفة'), ('loan', 'قسط سلفة'), ('insurance', 'تأمينات'), ('tax', 'ضرائب'), ('penalty', 'جزاء إداري'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='نوع الخصم')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('month', models.PositiveSmallIntegerField(verbose_name='الشهر')),
                ('year', models.PositiveSmallIntegerField(verbose_name='السنة')),
                ('is_visible_to_employee', models.BooleanField(default=True, verbose_name='ظاهر للموظف')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إدارية')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deductions', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'خصم',
                'verbose_name_plural': 'الخصومات',
                'ordering': ['-date'],
            },
        ),
    ]
