# Generated by Django 6.0.7 on 2026-07-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='attendance_mode',
            field=models.CharField(choices=[('fixed_shift', 'شيفت ثابت'), ('flexible_hours', 'ساعات مرنة'), ('field_worker', 'موظف ميداني'), ('rotating', 'شيفت متناوب')], default='fixed_shift', max_length=20, verbose_name='نظام الحضور'),
        ),
        migrations.AddField(
            model_name='employee',
            name='required_daily_hours',
            field=models.DecimalField(decimal_places=1, default=8, max_digits=4, verbose_name='ساعات العمل اليومية المطلوبة'),
        ),
    ]
