# Generated by Django 6.0.7 on 2026-07-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='language',
            field=models.CharField(choices=[('ar', 'العربية'), ('en', 'English')], default='ar', max_length=2, verbose_name='اللغة المفضلة'),
        ),
    ]
