# Generated by Django 6.0.7 on 2026-07-17 18:28

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_employee_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='country',
            field=django_countries.fields.CountryField(default='EG', max_length=2, verbose_name='الدولة'),
        ),
    ]
