# Generated by Django 6.0.7 on 2026-07-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_employee_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='currency',
            field=models.CharField(default='EGP', max_length=10, verbose_name='العملة'),
        ),
    ]
