# Generated by Django 6.0.7 on 2026-07-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_add_currency_to_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='instapay_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='salary_payment_method',
            field=models.CharField(blank=True, choices=[('none', 'Without method'), ('bank', 'Bank account'), ('instapay', 'InstaPay'), ('wallet', 'E-wallet')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='wallet_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='wallet_provider',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
