# Generated by Django 6.0.7 on 2026-07-26 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_employee_instapay_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='contract_duration_months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='للعقود المؤقتة - بديل عن تاريخ الانتهاء', null=True, verbose_name='مدة العقد بالشهور'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contract_start_date',
            field=models.DateField(blank=True, help_text='لو فاضي بيتحسب من تاريخ التعيين', null=True, verbose_name='تاريخ بداية العقد'),
        ),
        migrations.AddField(
            model_name='employee',
            name='probation_months',
            field=models.PositiveSmallIntegerField(default=3, help_text='0 = لا توجد فترة تجربة', verbose_name='مدة فترة التجربة بالشهور'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='contract_type',
            field=models.CharField(choices=[('permanent', 'دائم'), ('temporary', 'مؤقت'), ('training', 'تدريب'), ('freelance', 'حر'), ('part_time', 'دوام جزئي'), ('consultant', 'استشاري')], default='permanent', max_length=20, verbose_name='نوع العقد'),
        ),
    ]
