# Generated by Django 6.0.7 on 2026-07-27 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_company_payroll_cutoff_day_and_more'),
        ('employees', '0012_add_contract_and_probation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('file', models.FileField(max_length=500, upload_to='import_logs/%Y/%m/', verbose_name='الملف المرفوع')),
                ('original_filename', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الملف الأصلي')),
                ('status', models.CharField(default='completed', max_length=20, verbose_name='حالة الاستيراد')),
                ('created_count', models.IntegerField(default=0, verbose_name='عدد الموظفين الجدد')),
                ('updated_count', models.IntegerField(default=0, verbose_name='عدد الموظفين المحدثين')),
                ('error_count', models.IntegerField(default=0, verbose_name='عدد الأخطاء')),
                ('details', models.JSONField(blank=True, default=dict, null=True, verbose_name='تفاصيل الاستيراد')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل الاستيراد',
                'verbose_name_plural': 'سجلات الاستيراد',
                'ordering': ['-created_at'],
            },
        ),
    ]
