# Generated by Django 6.0.7 on 2026-07-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_importlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='attendance_mode',
            field=models.CharField(choices=[('fixed_shift', 'شيفت ثابت'), ('flexible_hours', 'ساعات مرنة'), ('field_worker', 'موظف ميداني'), ('multi_site', 'مواقع متعددة'), ('rotating', 'شيفت متناوب')], default='fixed_shift', max_length=20, verbose_name='نظام الحضور'),
        ),
    ]
