# Generated by Django 6.0.7 on 2026-07-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0014_alter_employee_attendance_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='worker_type',
            field=models.CharField(choices=[('office', 'مكتبي'), ('field_free', 'ميداني حر'), ('field_assigned', 'ميداني محدد')], default='office', help_text='مكتبي (بصمة من الشركة فقط)، ميداني حر (أي مكان)، ميداني محدد (مواقع معتمدة)', max_length=20, verbose_name='نوع الموظف'),
        ),
    ]
