# Generated by Django 6.0.7 on 2026-07-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0015_employee_worker_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='worker_type',
            field=models.CharField(blank=True, choices=[('office', 'مكتبي'), ('field_free', 'ميداني حر'), ('field_assigned', 'ميداني محدد')], help_text='مكتبي (بصمة من الشركة فقط)، ميداني حر (أي مكان)، ميداني محدد (مواقع معتمدة) - إجباري لتفعيل التطبيق', max_length=20, null=True, verbose_name='نوع الموظف'),
        ),
    ]
