# Generated by Django 6.0.7 on 2026-08-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0016_alter_employee_worker_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='insurance_base_salary',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='لو محدد يستخدم لحساب التأمينات (السياسات اللي أساسها employee_custom). لو فارغ يستخدم basic_salary.', max_digits=10, null=True, verbose_name='المرتب التأميني الخاص'),
        ),
    ]
