# Generated by Django 6.0.7 on 2026-08-10 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0017_add_insurance_base_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='insurance_base_salary',
        ),
    ]
