# Generated by Django 6.0.7 on 2026-08-11 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_companypolicy_tracking_interval_field_visit_minutes_and_more'),
        ('employees', '0018_remove_employee_insurance_base_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentjobtitlerule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_rule_branch', to='companies.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='departmentjobtitlerule',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='هل هذا المسمى الوظيفي مدير؟'),
        ),
        migrations.AddField(
            model_name='jobhierarchylevel',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hierarchy_branch', to='companies.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='jobhierarchylevel',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hierarchy_dept', to='companies.department', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='jobhierarchylevel',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='هل هذا المسمى الوظيفي مدير؟'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jt_branch_master', to='companies.branch', verbose_name='الفرع'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jt_dept_master', to='companies.department', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='هل هذا المسمى الوظيفي مدير؟'),
        ),
        migrations.AlterField(
            model_name='departmentjobtitlerule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_rule_dept', to='companies.department', verbose_name='القسم'),
        ),
    ]
