# Generated by Django 6.0.7 on 2026-09-01 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=10, verbose_name='المنصة')),
                ('latest_version_code', models.PositiveIntegerField(help_text='رقم النسخة الرقمي (مثال: 3 لو النسخة 1.1.0+3)', verbose_name='آخر رقم نسخة (versionCode)')),
                ('latest_version_name', models.CharField(help_text='مثال: 1.1.0', max_length=30, verbose_name='اسم النسخة')),
                ('min_required_version_code', models.PositiveIntegerField(help_text='أي نسخة أقل من الرقم ده هتضطر المستخدم يحدث فورًا', verbose_name='أقل نسخة مسموح تشتغل من غير تحديث إجباري')),
                ('store_url', models.URLField(default='https://play.google.com/store/apps/details?id=com.motionheployee', verbose_name='رابط المتجر')),
                ('update_message_ar', models.TextField(blank=True, default='يوجد تحديث جديد للتطبيق يحتوي على تحسينات مهمة.', verbose_name='رسالة التحديث بالعربي')),
                ('update_message_en', models.TextField(blank=True, default='A new app update is available with important improvements.', verbose_name='رسالة التحديث بالإنجليزي')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'نسخة التطبيق',
                'verbose_name_plural': 'إدارة نسخة التطبيق',
            },
        ),
    ]
