# Generated by Django 6.0.7 on 2026-07-10 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0010_alter_companypolicy_stealth_tracking_alert_after_minutes'),
        ('employees', '0005_add_stealth_tracking_to_employee'),
        ('requests_app', '0002_add_workflow_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvaldelegation',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='delegate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_received', to=settings.AUTH_USER_MODEL, verbose_name='المُفوَّض إليه'),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='delegator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delegations_given', to=settings.AUTH_USER_MODEL, verbose_name='المُفوِّض'),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='delegator_role',
            field=models.CharField(max_length=20, verbose_name='دور المُفوِّض'),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='end_date',
            field=models.DateField(verbose_name='إلى تاريخ'),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='reason',
            field=models.TextField(blank=True, verbose_name='السبب'),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='scope',
            field=models.CharField(choices=[('all_approvals', 'كل الموافقات'), ('team_only', 'فريقه فقط')], default='all_approvals', max_length=20, verbose_name='نطاق التفويض'),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='start_date',
            field=models.DateField(verbose_name='من تاريخ'),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='approvaldelegation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='escalation_enabled',
            field=models.BooleanField(default=True, verbose_name='تصعيد تلقائي لو المسؤول غير متاح'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='escalation_to',
            field=models.CharField(choices=[('hr_manager', 'مدير HR'), ('company_admin', 'صاحب الشركة')], default='hr_manager', max_length=20, verbose_name='التصعيد يروح لمين'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='notify_employee_on_each_step',
            field=models.BooleanField(default=True, verbose_name='إشعار الموظف في كل خطوة'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='request_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_flows', to='requests_app.requesttype', verbose_name='نوع الطلب'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='step_1_role',
            field=models.CharField(choices=[('skip', 'تخطي'), ('direct_manager', 'المدير المباشر'), ('hr_manager', 'مدير HR'), ('company_admin', 'صاحب الشركة')], default='direct_manager', max_length=20, verbose_name='الخطوة 1'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='step_2_role',
            field=models.CharField(choices=[('skip', 'تخطي'), ('direct_manager', 'المدير المباشر'), ('hr_manager', 'مدير HR'), ('company_admin', 'صاحب الشركة')], default='hr_manager', max_length=20, verbose_name='الخطوة 2'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='step_3_role',
            field=models.CharField(choices=[('skip', 'تخطي'), ('direct_manager', 'المدير المباشر'), ('hr_manager', 'مدير HR'), ('company_admin', 'صاحب الشركة')], default='skip', max_length=20, verbose_name='الخطوة 3'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='approvalflow',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='current_step',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='الخطوة الحالية'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='step_1_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الخطوة 1'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='step_1_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step1_approvals', to=settings.AUTH_USER_MODEL, verbose_name='الخطوة 1 بواسطة'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='step_1_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الخطوة 1'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='step_1_status',
            field=models.CharField(blank=True, choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق'), ('rejected', 'مرفوض'), ('skipped', 'تخطي')], default='pending', max_length=20, verbose_name='حالة الخطوة 1'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='step_2_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الخطوة 2'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='step_2_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step2_approvals', to=settings.AUTH_USER_MODEL, verbose_name='الخطوة 2 بواسطة'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='step_2_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الخطوة 2'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='step_2_status',
            field=models.CharField(blank=True, choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق'), ('rejected', 'مرفوض'), ('skipped', 'تخطي')], default='', max_length=20, verbose_name='حالة الخطوة 2'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='step_3_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت الخطوة 3'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='step_3_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='step3_approvals', to=settings.AUTH_USER_MODEL, verbose_name='الخطوة 3 بواسطة'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='step_3_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات الخطوة 3'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='step_3_status',
            field=models.CharField(blank=True, choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق'), ('rejected', 'مرفوض'), ('skipped', 'تخطي')], default='', max_length=20, verbose_name='حالة الخطوة 3'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='substitute_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_requests', to='employees.employee', verbose_name='البديل'),
        ),
        migrations.AlterField(
            model_name='employeerequest',
            name='substitute_notified',
            field=models.BooleanField(default=False, verbose_name='تم إشعار البديل'),
        ),
    ]
