# Generated by Django 6.0.7 on 2026-07-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_permissionpolicy_permissionusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequest',
            name='duration_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='عدد الساعات'),
        ),
    ]
