# Generated by Django 6.0.7 on 2026-07-15 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0005_employeerequest_duration_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestcategory',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='description_en',
            field=models.TextField(blank=True, default='', verbose_name='الوصف بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='الاسم بالإنجليزية'),
        ),
        migrations.AddField(
            model_name='requesttype',
            name='permission_kind',
            field=models.CharField(choices=[('none', 'ليس إذن حضور'), ('late_arrival', 'إذن تأخير'), ('early_leave', 'إذن خروج مبكر')], db_index=True, default='none', max_length=20, verbose_name='نوع إذن الحضور'),
        ),
        migrations.AlterField(
            model_name='requestcategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم بالعربية'),
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف بالعربية'),
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الاسم بالعربية'),
        ),
    ]
