# Generated by Django 6.0.7 on 2026-07-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0006_requestcategory_name_en_requesttype_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequest',
            name='actual_used_hours',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='الساعات المستخدمة فعليًا'),
        ),
        migrations.AddField(
            model_name='employeerequest',
            name='permission_used_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت استخدام الإذن فعليًا'),
        ),
    ]
