# Generated by Django 6.0.7 on 2026-07-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0007_employeerequest_actual_used_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequest',
            name='permission_time',
            field=models.TimeField(blank=True, null=True, verbose_name='وقت الإذن'),
        ),
    ]
