# Generated by Django 6.0.7 on 2026-07-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0008_employeerequest_permission_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='form_schema',
            field=models.JSONField(blank=True, default=dict, help_text='الحقول الديناميكية المطلوبة لهذا النوع من الطلبات', verbose_name='مخطط الفورمة'),
        ),
    ]
