# Generated by Django 6.0.7 on 2026-07-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0009_request_type_form_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeerequest',
            name='form_data',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات الفورمة الديناميكية'),
        ),
    ]
