"""
Leave Types Templates - أنواع الإجازات الافتراضية
يتم إضافتها تلقائياً لأي شركة جديدة عند إنشائها
العميل يقدر يعدل الأيام، الخصائص، أو يضيف/يمسح أنواع
"""

DEFAULT_LEAVE_TYPES = [
    {
        'name': 'إجازة سنوية',
        'name_en': 'Annual Leave',
        'category': 'annual',
        'days_allowed': 21,
        'is_paid': True,
        'requires_approval': True,
        'requires_document': False,
        'carry_forward': True,
        'max_carry_days': 5,
        'color': '#4CAF50',
        'gender_restriction': 'all',
        'description': 'الإجازة السنوية المستحقة للموظف',
        'is_active': True,
    },
    {
        'name': 'إجازة مرضية',
        'name_en': 'Sick Leave',
        'category': 'sick',
        'days_allowed': 14,
        'is_paid': True,
        'requires_approval': True,
        'requires_document': True,
        'carry_forward': False,
        'max_carry_days': 0,
        'color': '#F44336',
        'gender_restriction': 'all',
        'description': 'إجازة مرضية بتقرير طبي',
        'is_active': True,
    },
    {
        'name': 'إجازة طارئة',
        'name_en': 'Emergency Leave',
        'category': 'emergency',
        'days_allowed': 7,
        'is_paid': True,
        'requires_approval': True,
        'requires_document': False,
        'carry_forward': False,
        'max_carry_days': 0,
        'color': '#FF9800',
        'gender_restriction': 'all',
        'description': 'إجازة طارئة لظروف قاهرة',
        'is_active': True,
    },
    {
        'name': 'إجازة بدون مرتب',
        'name_en': 'Unpaid Leave',
        'category': 'unpaid',
        'days_allowed': 30,
        'is_paid': False,
        'requires_approval': True,
        'requires_document': False,
        'carry_forward': False,
        'max_carry_days': 0,
        'color': '#9E9E9E',
        'gender_restriction': 'all',
        'description': 'إجازة بدون أجر',
        'is_active': True,
    },
    {
        'name': 'إجازة أمومة',
        'name_en': 'Maternity Leave',
        'category': 'maternity',
        'days_allowed': 90,
        'is_paid': True,
        'requires_approval': True,
        'requires_document': True,
        'carry_forward': False,
        'max_carry_days': 0,
        'color': '#E91E63',
        'gender_restriction': 'female',
        'description': 'إجازة الوضع للموظفات',
        'is_active': True,
    },
    {
        'name': 'إجازة عارضة',
        'name_en': 'Casual Leave',
        'category': 'casual',
        'days_allowed': 6,
        'is_paid': True,
        'requires_approval': True,
        'requires_document': False,
        'carry_forward': False,
        'max_carry_days': 0,
        'color': '#00BCD4',
        'gender_restriction': 'all',
        'description': 'إجازة عارضة قصيرة المدة',
        'is_active': True,
    },
    {
        'name': 'إجازة زواج',
        'name_en': 'Marriage Leave',
        'category': 'marriage',
        'days_allowed': 3,
        'is_paid': True,
        'requires_approval': True,
        'requires_document': False,
        'carry_forward': False,
        'max_carry_days': 0,
        'color': '#9C27B0',
        'gender_restriction': 'all',
        'description': 'إجازة مناسبة الزواج',
        'is_active': True,
    },
    {
        'name': 'إجازة وفاة',
        'name_en': 'Bereavement Leave',
        'category': 'bereavement',
        'days_allowed': 3,
        'is_paid': True,
        'requires_approval': True,
        'requires_document': False,
        'carry_forward': False,
        'max_carry_days': 0,
        'color': '#607D8B',
        'gender_restriction': 'all',
        'description': 'إجازة وفاة أحد المقربين',
        'is_active': True,
    },
    {
        'name': 'إجازة حج',
        'name_en': 'Hajj Leave',
        'category': 'hajj',
        'days_allowed': 21,
        'is_paid': True,
        'requires_approval': True,
        'requires_document': False,
        'carry_forward': False,
        'max_carry_days': 0,
        'color': '#795548',
        'gender_restriction': 'all',
        'description': 'إجازة أداء فريضة الحج',
        'is_active': True,
    },
    {
        'name': 'إجازة أخرى',
        'name_en': 'Other Leave',
        'category': 'other',
        'days_allowed': 7,
        'is_paid': True,
        'requires_approval': True,
        'requires_document': False,
        'carry_forward': False,
        'max_carry_days': 0,
        'color': '#FF5722',
        'gender_restriction': 'all',
        'description': 'إجازات خاصة وأعياد دينية',
        'is_active': True,
    },
]
