# Generated by Django 6.0.7 on 2026-07-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_push_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
