# Generated by Django 6.0.7 on 2026-07-11 22:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_pushsubscription_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإشعار')),
                ('message', models.TextField(help_text='اكتب تفاصيل الإشعار بوضوح', verbose_name='محتوى الإشعار')),
                ('announcement_type', models.CharField(choices=[('feature', '✨ ميزة جديدة'), ('update', '🔄 تحديث'), ('maintenance', '🔧 صيانة'), ('offer', '🎁 عرض خاص'), ('general', '📢 إعلان عام'), ('warning', '⚠️ تنبيه هام')], default='general', max_length=20, verbose_name='نوع الإشعار')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'مرتفع'), ('urgent', '🚨 عاجل')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('action_url', models.URLField(blank=True, help_text='لو فيه رابط للمزيد من التفاصيل', null=True, verbose_name='رابط الإجراء (اختياري)')),
                ('action_text', models.CharField(blank=True, default='اعرف المزيد', max_length=50, verbose_name='نص الزر')),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء (اختياري)')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('send_push', models.BooleanField(default=True, verbose_name='إرسال Push Notification للموبايل')),
                ('send_to_all', models.BooleanField(default=True, verbose_name='إرسال لكل المشتركين')),
                ('total_sent', models.IntegerField(default=0, verbose_name='عدد المرسل إليهم')),
                ('total_read', models.IntegerField(default=0, verbose_name='عدد القراءات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
            ],
            options={
                'verbose_name': 'إشعار نظام',
                'verbose_name_plural': '📢 إشعارات النظام',
                'ordering': ['-publish_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reads', to='accounts.systemannouncement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'announcement')},
            },
        ),
    ]
