# Generated by Django 6.0.7 on 2026-07-11 22:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_systemannouncement_userannouncementread'),
        ('companies', '0015_charter_digital_signature'),
        ('employees', '0007_employee_folder'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAnnouncement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الإشعار')),
                ('message', models.TextField(verbose_name='محتوى الإشعار')),
                ('announcement_type', models.CharField(choices=[('holiday', '🏖️ إجازة رسمية'), ('meeting', '👥 اجتماع'), ('event', '🎉 فعالية'), ('policy', '📋 سياسة جديدة'), ('reminder', '🔔 تذكير'), ('urgent', '🚨 عاجل'), ('general', '📢 إعلان عام'), ('celebration', '🎊 مناسبة')], default='general', max_length=20, verbose_name='نوع الإشعار')),
                ('priority', models.CharField(choices=[('low', 'منخفض'), ('medium', 'متوسط'), ('high', 'مرتفع'), ('urgent', '🚨 عاجل')], default='medium', max_length=10, verbose_name='الأولوية')),
                ('target_type', models.CharField(choices=[('all', 'كل الموظفين'), ('specific', 'موظفين محددين'), ('by_job_title', 'حسب المسمى الوظيفي'), ('by_department', 'حسب الإدارة'), ('by_branch', 'حسب الفرع')], default='all', max_length=20, verbose_name='نوع الاستهداف')),
                ('target_job_titles', models.CharField(blank=True, help_text='مثال: مندوب مبيعات, مدير, محاسب', max_length=500, verbose_name='المسميات الوظيفية (مفصولة بفاصلة)')),
                ('excluded_job_titles', models.CharField(blank=True, max_length=500, verbose_name='🚫 مسميات مستثناة (مفصولة بفاصلة)')),
                ('publish_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ النشر')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الانتهاء (اختياري)')),
                ('send_push', models.BooleanField(default=True, verbose_name='إرسال Push Notification')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('total_sent', models.IntegerField(default=0, verbose_name='عدد المرسل إليهم')),
                ('total_read', models.IntegerField(default=0, verbose_name='عدد القراءات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_announcements', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('excluded_departments', models.ManyToManyField(blank=True, related_name='excluded_from_announcements', to='companies.department', verbose_name='🚫 إدارات مستثناة')),
                ('excluded_employees', models.ManyToManyField(blank=True, related_name='excluded_from_announcements', to='employees.employee', verbose_name='🚫 موظفون مستثنون')),
                ('target_branches', models.ManyToManyField(blank=True, related_name='received_announcements', to='companies.branch', verbose_name='الفروع المستهدفة')),
                ('target_departments', models.ManyToManyField(blank=True, related_name='received_announcements', to='companies.department', verbose_name='الإدارات المستهدفة')),
                ('target_employees', models.ManyToManyField(blank=True, related_name='received_announcements', to='employees.employee', verbose_name='الموظفون المستهدفون')),
            ],
            options={
                'verbose_name': 'إشعار شركة',
                'verbose_name_plural': '🏢 إشعارات الشركات',
                'ordering': ['-publish_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAnnouncementRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='accounts.companyannouncement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_reads', to='employees.employee')),
            ],
            options={
                'verbose_name': 'قراءة إشعار',
                'verbose_name_plural': 'قراءات الإشعارات',
                'unique_together': {('employee', 'announcement')},
            },
        ),
    ]
