# Generated by Django 6.0.7 on 2026-07-15 15:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_fcmdevicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('body', models.TextField(verbose_name='النص')),
                ('notification_type', models.CharField(choices=[('new_request', 'طلب جديد'), ('new_leave', 'إجازة جديدة'), ('request_approved', 'موافقة على طلب'), ('request_rejected', 'رفض طلب'), ('leave_approved', 'موافقة على إجازة'), ('leave_rejected', 'رفض إجازة'), ('geofence_violation', 'مخالفة نطاق'), ('general', 'عام')], default='general', max_length=50, verbose_name='النوع')),
                ('is_read', models.BooleanField(default=False, verbose_name='مقروء')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'إشعار',
                'verbose_name_plural': 'الإشعارات',
                'ordering': ['-created_at'],
            },
        ),
    ]
