# Generated by Django 6.0.7 on 2026-07-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_notificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationlog',
            name='data',
            field=models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية'),
        ),
    ]
