# Generated by Django 6.0.7 on 2026-07-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_notificationlog_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyannouncement',
            name='requires_confirmation',
            field=models.BooleanField(default=False, verbose_name='يتطلب تأكيد القراءة'),
        ),
    ]
