# Generated by Django 6.0.7 on 2026-07-18 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_add_confirmation_to_announcement'),
    ]

    operations = [
        migrations.AddField(
            model_name='fcmdevicetoken',
            name='preferred_language',
            field=models.CharField(default='ar', max_length=10, verbose_name='اللغة المفضلة'),
        ),
    ]
