# Generated by Django 6.0.7 on 2026-07-22 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_language_to_fcm_token'),
        ('companies', '0018_fix_charter_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الدور')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to='companies.company')),
            ],
            options={
                'verbose_name': 'دور مخصص',
                'verbose_name_plural': 'الأدوار المخصصة',
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('employees.view', 'عرض الموظفين'), ('employees.add', 'إضافة موظف'), ('employees.edit', 'تعديل موظف'), ('employees.delete', 'حذف موظف'), ('employees.transfer', 'نقل موظف'), ('attendance.view', 'عرض الحضور'), ('attendance.edit', 'تعديل الحضور'), ('leaves.view', 'عرض الإجازات'), ('leaves.approve', 'اعتماد الإجازات'), ('requests.view', 'عرض الطلبات'), ('requests.approve', 'اعتماد الطلبات'), ('payroll.view', 'عرض المرتبات'), ('payroll.edit', 'تعديل المرتبات'), ('reports.view', 'عرض التقارير'), ('reports.export', 'تصدير التقارير'), ('missions.view', 'عرض المهام'), ('missions.manage', 'إدارة المهام'), ('company.view', 'عرض إعدادات الشركة'), ('company.edit', 'تعديل إعدادات الشركة')], max_length=50)),
                ('scope', models.CharField(choices=[('self', 'نفسه فقط'), ('team', 'فريقه فقط'), ('dept', 'قسمه فقط'), ('company', 'كل الشركة')], default='company', max_length=10)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='accounts.customrole')),
            ],
            options={
                'verbose_name': 'صلاحية دور',
                'verbose_name_plural': 'صلاحيات الأدوار',
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserPermissionOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('employees.view', 'عرض الموظفين'), ('employees.add', 'إضافة موظف'), ('employees.edit', 'تعديل موظف'), ('employees.delete', 'حذف موظف'), ('employees.transfer', 'نقل موظف'), ('attendance.view', 'عرض الحضور'), ('attendance.edit', 'تعديل الحضور'), ('leaves.view', 'عرض الإجازات'), ('leaves.approve', 'اعتماد الإجازات'), ('requests.view', 'عرض الطلبات'), ('requests.approve', 'اعتماد الطلبات'), ('payroll.view', 'عرض المرتبات'), ('payroll.edit', 'تعديل المرتبات'), ('reports.view', 'عرض التقارير'), ('reports.export', 'تصدير التقارير'), ('missions.view', 'عرض المهام'), ('missions.manage', 'إدارة المهام'), ('company.view', 'عرض إعدادات الشركة'), ('company.edit', 'تعديل إعدادات الشركة')], max_length=50)),
                ('scope', models.CharField(choices=[('self', 'نفسه فقط'), ('team', 'فريقه فقط'), ('dept', 'قسمه فقط'), ('company', 'كل الشركة')], default='company', max_length=10)),
                ('is_granted', models.BooleanField(default=True, verbose_name='ممنوحة أم ممنوعة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'استثناء صلاحية',
                'verbose_name_plural': 'استثناءات الصلاحيات',
                'unique_together': {('user', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.customrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'دور المستخدم',
                'verbose_name_plural': 'أدوار المستخدمين',
                'unique_together': {('user', 'role')},
            },
        ),
    ]
