# Generated by Django 6.0.7 on 2026-08-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customrole_rolepermission_userpermissionoverride_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permission',
            field=models.CharField(choices=[('employees.view', 'عرض الموظفين'), ('employees.add', 'إضافة موظف'), ('employees.edit', 'تعديل موظف'), ('employees.delete', 'حذف موظف'), ('employees.transfer', 'نقل موظف'), ('attendance.view', 'عرض الحضور'), ('attendance.edit', 'تعديل الحضور'), ('leaves.view', 'عرض الإجازات'), ('leaves.approve', 'اعتماد الإجازات'), ('requests.view', 'عرض الطلبات'), ('requests.approve', 'اعتماد الطلبات'), ('payroll.view', 'عرض المرتبات'), ('payroll.edit', 'تعديل المرتبات'), ('reports.view', 'عرض التقارير'), ('reports.export', 'تصدير التقارير'), ('missions.view', 'عرض المهام'), ('missions.manage', 'إدارة المهام'), ('company.view', 'عرض إعدادات الشركة'), ('company.edit', 'تعديل إعدادات الشركة'), ('departments.view', 'عرض الأقسام'), ('departments.add', 'إضافة قسم'), ('departments.edit', 'تعديل قسم'), ('departments.delete', 'حذف قسم'), ('departments.transfer_employees', 'نقل موظفين بين الأقسام'), ('offboarding.execute', 'إنهاء خدمة موظف أو مدير'), ('shifts.view', 'عرض الشيفتات'), ('shifts.manage', 'إدارة الشيفتات'), ('policies.view', 'عرض السياسات'), ('policies.manage', 'إدارة السياسات'), ('holidays.view', 'عرض الإجازات الرسمية'), ('holidays.manage', 'إدارة الإجازات الرسمية'), ('tracking.view', 'عرض التتبع والمواقع'), ('tracking.manage', 'إدارة التتبع'), ('payroll.view_own', 'عرض مرتبي فقط'), ('attendance.checkin', 'تسجيل الحضور والانصراف'), ('leaves.request', 'تقديم طلب إجازة'), ('requests.submit', 'تقديم طلبات'), ('profile.view', 'عرض الملف الشخصي'), ('profile.edit_basic', 'تعديل البيانات الأساسية'), ('missions.view_own', 'عرض مهامي فقط'), ('roles.manage', 'إدارة الأدوار والصلاحيات')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userpermissionoverride',
            name='permission',
            field=models.CharField(choices=[('employees.view', 'عرض الموظفين'), ('employees.add', 'إضافة موظف'), ('employees.edit', 'تعديل موظف'), ('employees.delete', 'حذف موظف'), ('employees.transfer', 'نقل موظف'), ('attendance.view', 'عرض الحضور'), ('attendance.edit', 'تعديل الحضور'), ('leaves.view', 'عرض الإجازات'), ('leaves.approve', 'اعتماد الإجازات'), ('requests.view', 'عرض الطلبات'), ('requests.approve', 'اعتماد الطلبات'), ('payroll.view', 'عرض المرتبات'), ('payroll.edit', 'تعديل المرتبات'), ('reports.view', 'عرض التقارير'), ('reports.export', 'تصدير التقارير'), ('missions.view', 'عرض المهام'), ('missions.manage', 'إدارة المهام'), ('company.view', 'عرض إعدادات الشركة'), ('company.edit', 'تعديل إعدادات الشركة'), ('departments.view', 'عرض الأقسام'), ('departments.add', 'إضافة قسم'), ('departments.edit', 'تعديل قسم'), ('departments.delete', 'حذف قسم'), ('departments.transfer_employees', 'نقل موظفين بين الأقسام'), ('offboarding.execute', 'إنهاء خدمة موظف أو مدير'), ('shifts.view', 'عرض الشيفتات'), ('shifts.manage', 'إدارة الشيفتات'), ('policies.view', 'عرض السياسات'), ('policies.manage', 'إدارة السياسات'), ('holidays.view', 'عرض الإجازات الرسمية'), ('holidays.manage', 'إدارة الإجازات الرسمية'), ('tracking.view', 'عرض التتبع والمواقع'), ('tracking.manage', 'إدارة التتبع'), ('payroll.view_own', 'عرض مرتبي فقط'), ('attendance.checkin', 'تسجيل الحضور والانصراف'), ('leaves.request', 'تقديم طلب إجازة'), ('requests.submit', 'تقديم طلبات'), ('profile.view', 'عرض الملف الشخصي'), ('profile.edit_basic', 'تعديل البيانات الأساسية'), ('missions.view_own', 'عرض مهامي فقط'), ('roles.manage', 'إدارة الأدوار والصلاحيات')], max_length=50),
        ),
    ]
