# Generated by Django 6.0.7 on 2026-08-15 16:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_rolepermission_permission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, verbose_name='معرف الجهاز')),
                ('device_name', models.CharField(blank=True, default='', max_length=200, verbose_name='اسم الجهاز')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], default='android', max_length=20, verbose_name='نوع الجهاز')),
                ('status', models.CharField(choices=[('pending', 'في انتظار الموافقة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('revoked', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('is_first_device', models.BooleanField(default=False, verbose_name='أول جهاز')),
                ('auto_attendance_enabled', models.BooleanField(default=False, verbose_name='Auto Attendance مفعّل')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الموافقة')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر دخول')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_devices', to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة بواسطة')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trusted_devices', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'جهاز موثوق',
                'verbose_name_plural': 'الأجهزة الموثوقة',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
