# Generated by Django 6.0.7 on 2026-07-10 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companypolicy'),
        ('employees', '0003_deduction'),
        ('leaves', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='leavebalance',
            name='unique_leave_balance',
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to='employees.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='leaves.leavetype', verbose_name='نوع الإجازة'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='pending_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='الأيام قيد الانتظار'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='total_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='إجمالي الأيام'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='used_days',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='الأيام المستخدمة'),
        ),
        migrations.AlterField(
            model_name='leavebalance',
            name='year',
            field=models.PositiveSmallIntegerField(default=2025, verbose_name='السنة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='days_count',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4, verbose_name='عدد الأيام'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='leave_documents/', verbose_name='وثيقة مرفقة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to='employees.employee', verbose_name='الموظف'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='end_date',
            field=models.DateField(verbose_name='إلى تاريخ'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='leaves.leavetype', verbose_name='نوع الإجازة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reason',
            field=models.TextField(verbose_name='السبب'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='review_notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات المراجع'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_leaves', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='start_date',
            field=models.DateField(verbose_name='من تاريخ'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='carry_forward',
            field=models.BooleanField(default=False, verbose_name='ترحيل للسنة القادمة'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='color',
            field=models.CharField(default='#06B6D4', max_length=7, verbose_name='اللون'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='days_allowed',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = بدون حد', verbose_name='عدد الأيام المسموحة سنوياً'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='بمرتب'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='max_carry_days',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='أقصى أيام ترحيل'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='requires_approval',
            field=models.BooleanField(default=True, verbose_name='تحتاج موافقة'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='requires_document',
            field=models.BooleanField(default=False, verbose_name='تحتاج وثيقة'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة'),
        ),
        migrations.AlterUniqueTogether(
            name='leavebalance',
            unique_together={('company', 'employee', 'leave_type', 'year')},
        ),
    ]
