# Generated by Django 6.0.7 on 2026-07-24 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_department_default_role_alter_branch_default_role'),
        ('employees', '0011_employee_instapay_phone_and_more'),
        ('leaves', '0002_remove_leavebalance_unique_leave_balance_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRecallRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('recall_date', models.DateField(verbose_name='يوم الاستدعاء')),
                ('reason', models.TextField(verbose_name='سبب الاستدعاء')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات المراجع')),
                ('hr_notified', models.BooleanField(default=False, verbose_name='تم إشعار HR')),
                ('balance_restored', models.BooleanField(default=False, verbose_name='تم إرجاع الرصيد')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_recall_requests', to='employees.employee', verbose_name='الموظف')),
                ('leave_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recall_requests', to='leaves.leaverequest', verbose_name='طلب الإجازة الأصلي')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_recall_requests_made', to=settings.AUTH_USER_MODEL, verbose_name='طلب بواسطة')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_recall_reviews', to=settings.AUTH_USER_MODEL, verbose_name='وافق/رفض بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'استدعاء من إجازة',
                'verbose_name_plural': 'استدعاءات من الإجازات',
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'recall_date')},
            },
        ),
    ]
