# Generated by Django 6.0.7 on 2026-07-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0003_leaverecallrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='half_day_type',
            field=models.CharField(blank=True, choices=[('morning', 'صباحي'), ('afternoon', 'مسائي')], default='', max_length=20, verbose_name='نوع نصف اليوم'),
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='عدد ساعات الإجازة'),
        ),
    ]
