# Generated by Django 6.0.7 on 2026-07-26 23:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_company_payroll_cutoff_day_and_more'),
        ('employees', '0012_add_contract_and_probation_fields'),
        ('leaves', '0004_leave_request_half_day'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveBalanceAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('year', models.PositiveSmallIntegerField(verbose_name='السنة')),
                ('adjustment_type', models.CharField(choices=[('opening_balance', 'رصيد افتتاحي'), ('manual_add', 'إضافة يدوية'), ('manual_deduct', 'خصم يدوي'), ('carry_forward', 'ترحيل من السنة السابقة'), ('cash_settlement', 'تسوية نقدية'), ('policy_reset', 'إعادة ضبط من السياسة')], max_length=20, verbose_name='نوع التعديل')),
                ('days', models.DecimalField(decimal_places=1, help_text='موجب = إضافة / سالب = خصم', max_digits=6, verbose_name='عدد الأيام')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_balance_adjustments_made', to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balance_adjustments', to='employees.employee', verbose_name='الموظف')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balance_adjustments', to='leaves.leavetype', verbose_name='نوع الإجازة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'تعديل رصيد إجازة',
                'verbose_name_plural': 'تعديلات أرصدة الإجازات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('name', models.CharField(max_length=200, verbose_name='اسم السياسة')),
                ('effective_from', models.DateField(verbose_name='سارية من')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='سارية لحد')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('active', 'نشط'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('probation_months', models.PositiveSmallIntegerField(default=3, help_text='0 = لا توجد فترة تجربة', verbose_name='فترة التجربة بالشهور')),
                ('probation_leave_mode', models.CharField(choices=[('blocked', 'ممنوع الإجازات'), ('limited_types', 'أنواع محددة فقط'), ('accrue_no_use', 'يتحسب بس مايتستخدمش'), ('normal', 'عادي')], default='blocked', max_length=20, verbose_name='الإجازات في فترة التجربة')),
                ('accrual_mode', models.CharField(choices=[('annual_lump', 'دفعة واحدة أول السنة'), ('monthly', 'شهري')], default='annual_lump', max_length=20, verbose_name='طريقة منح الرصيد')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_policies', to=settings.AUTH_USER_MODEL, verbose_name='وافق بواسطة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'سياسة إجازات',
                'verbose_name_plural': 'سياسات الإجازات',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicyTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_months', models.PositiveSmallIntegerField(default=0, verbose_name='من الشهر')),
                ('to_months', models.PositiveSmallIntegerField(blank=True, help_text='فاضي = بلا حد أقصى', null=True, verbose_name='لحد الشهر')),
                ('annual_entitlement_days', models.DecimalField(decimal_places=1, default=21, max_digits=5, verbose_name='الاستحقاق السنوي بالأيام')),
                ('description', models.TextField(blank=True, verbose_name='وصف الشريحة')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='leaves.leavepolicy', verbose_name='السياسة')),
            ],
            options={
                'verbose_name': 'شريحة خدمة',
                'verbose_name_plural': 'شرائح الخدمة',
                'ordering': ['from_months'],
            },
        ),
        migrations.CreateModel(
            name='LeavePolicyTypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('entitlement_mode', models.CharField(choices=[('from_service_tier', 'من شريحة مدة الخدمة'), ('fixed_days', 'عدد ثابت'), ('subset_of_parent', 'جزء من نوع تاني')], default='from_service_tier', max_length=20, verbose_name='مصدر الرصيد')),
                ('fixed_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='عدد أيام ثابت')),
                ('subset_limit_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='الحد الأقصى كجزء من الأب')),
                ('requires_balance', models.BooleanField(default=True, verbose_name='يحتاج رصيد كافي')),
                ('allow_negative_balance', models.BooleanField(default=False, verbose_name='مسموح بالسالب')),
                ('negative_limit_days', models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='حد الرصيد السالب')),
                ('allow_half_day', models.BooleanField(default=True, verbose_name='مسموح بنص يوم')),
                ('allow_hourly', models.BooleanField(default=False, verbose_name='مسموح بالساعة')),
                ('max_days_per_request', models.PositiveSmallIntegerField(default=0, help_text='0 = بلا حد', verbose_name='أقصى أيام في الطلب الواحد')),
                ('max_requests_per_year', models.PositiveSmallIntegerField(default=0, help_text='0 = بلا حد', verbose_name='أقصى طلبات في السنة')),
                ('can_use_during_probation', models.BooleanField(default=False, verbose_name='مسموح في فترة التجربة')),
                ('carry_mode', models.CharField(choices=[('none', 'لا ترحيل'), ('all', 'ترحيل كامل'), ('percentage', 'نسبة فقط'), ('percentage_with_cap', 'نسبة بحد أقصى'), ('cash_only', 'مقابل نقدي بدون ترحيل'), ('carry_and_cash_remainder', 'جزء يترحل والباقي فلوس')], default='none', max_length=30, verbose_name='سياسة الترحيل')),
                ('carry_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='نسبة الترحيل %')),
                ('carry_max_days', models.DecimalField(decimal_places=1, default=0, help_text='0 = بلا حد', max_digits=5, verbose_name='أقصى أيام ترحيل')),
                ('cash_compensation_enabled', models.BooleanField(default=False, verbose_name='مقابل نقدي مفعّل')),
                ('cash_compensation_basis', models.CharField(choices=[('basic_salary', 'المرتب الأساسي'), ('gross_fixed', 'الأساسي + البدلات الثابتة'), ('daily_rate', 'المعدل اليومي')], default='basic_salary', max_length=20, verbose_name='أساس المقابل النقدي')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_rules', to='leaves.leavetype', verbose_name='نوع الإجازة')),
                ('parent_leave_type', models.ForeignKey(blank=True, help_text='لو الاستحقاق جزء من نوع تاني', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_policy_rules', to='leaves.leavetype', verbose_name='النوع الأب')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_rules', to='leaves.leavepolicy', verbose_name='السياسة')),
            ],
            options={
                'verbose_name': 'قاعدة نوع إجازة',
                'verbose_name_plural': 'قواعد أنواع الإجازات',
                'unique_together': {('policy', 'leave_type')},
            },
        ),
    ]
