# Generated by Django 6.0.7 on 2026-07-31 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_companypolicy_tracking_interval_field_visit_minutes_and_more'),
        ('employees', '0016_alter_employee_worker_type'),
        ('leaves', '0005_add_leave_policy_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الإجازة')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(verbose_name='إلى تاريخ')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('send_notification', models.BooleanField(default=True, verbose_name='إرسال إشعار')),
                ('remind_day_before', models.BooleanField(default=False, verbose_name='تذكير قبل بيوم')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'إجازة رسمية',
                'verbose_name_plural': 'الإجازات الرسمية',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='OfficialHolidayRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('scope', models.CharField(choices=[('company', 'الشركة كلها'), ('branch', 'فرع محدد'), ('department', 'قسم محدد'), ('employees', 'موظفين محددين')], default='company', max_length=20, verbose_name='يتطبق على')),
                ('treatment', models.CharField(choices=[('paid_leave', 'إجازة مدفوعة'), ('work_with_bonus', 'عمل بمقابل إضافي'), ('normal_work', 'يوم عمل عادي')], default='paid_leave', max_length=20, verbose_name='نوع المعاملة')),
                ('bonus_calc_method', models.CharField(blank=True, choices=[('fixed_amount', 'مبلغ ثابت'), ('salary_percentage', 'نسبة من المرتب الأساسي'), ('day_multiplier', 'مضاعف أجر اليوم')], default='', max_length=20, verbose_name='طريقة حساب المقابل')),
                ('bonus_fixed_amount', models.DecimalField(decimal_places=2, default=0, help_text='مبلغ محدد بيتضاف على مرتب الموظف عن كل يوم اشتغله في الإجازة الرسمية', max_digits=10, verbose_name='المبلغ الثابت')),
                ('bonus_salary_percentage', models.DecimalField(decimal_places=2, default=0, help_text='نسبة مئوية من المرتب الأساسي الشهري بتتحسب عن كل يوم اشتغله في الإجازة الرسمية', max_digits=5, verbose_name='النسبة من المرتب %')),
                ('bonus_day_multiplier', models.DecimalField(decimal_places=2, default=2.0, help_text='أجر اليوم العادي مضروب في المضاعف ده', max_digits=4, verbose_name='مضاعف أجر اليوم')),
                ('priority', models.PositiveSmallIntegerField(default=10, help_text='رقم أصغر = أولوية أعلى. لو موظف ينطبق عليه أكتر من قاعدة، الأولوية الأعلى هي اللي تتطبق', verbose_name='الأولوية')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.department', verbose_name='القسم')),
                ('employees', models.ManyToManyField(blank=True, related_name='holiday_rules', to='employees.employee', verbose_name='موظفين محددين')),
                ('holiday', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='leaves.officialholiday', verbose_name='الإجازة الرسمية')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'قاعدة إجازة رسمية',
                'verbose_name_plural': 'قواعد الإجازات الرسمية',
                'ordering': ['priority', 'id'],
            },
        ),
    ]
