# Generated by Django 6.0.7 on 2026-08-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0006_add_official_holiday_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Name (English)'),
        ),
    ]
