# Generated by Django 6.0.7 on 2026-08-06 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0007_leavetype_name_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='gender_restriction',
            field=models.CharField(choices=[('all', 'الجميع'), ('male', 'ذكور فقط'), ('female', 'إناث فقط')], default='all', max_length=10, verbose_name='مخصصة لـ'),
        ),
    ]
