# Generated by Django 6.0.7 on 2026-08-15 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0019_departmentjobtitlerule_branch_and_more'),
        ('leaves', '0008_leavetype_gender_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='substitute_employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substituted_leaves', to='employees.employee', verbose_name='الموظف البديل'),
        ),
        migrations.AlterField(
            model_name='leavetype',
            name='category',
            field=models.CharField(choices=[('annual', 'إجازة سنوية'), ('sick', 'إجازة مرضية'), ('emergency', 'إجازة طارئة'), ('maternity', 'إجازة أمومة'), ('unpaid', 'إجازة بدون مرتب'), ('casual', 'إجازة عارضة'), ('marriage', 'إجازة زواج'), ('bereavement', 'إجازة وفاة'), ('hajj', 'إجازة حج'), ('other', 'أخرى')], default='other', max_length=20, verbose_name='الفئة'),
        ),
    ]
