# Generated by Django 6.0.7 on 2026-08-15 11:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_department_branch'),
        ('employees', '0019_departmentjobtitlerule_branch_and_more'),
        ('leaves', '0009_leaverequest_substitute_employee_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerSubstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(verbose_name='إلى تاريخ')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('leave_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='manager_substitution', to='leaves.leaverequest', verbose_name='طلب الإجازة')),
                ('manager_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_as_manager', to='employees.employee', verbose_name='المدير الغايب')),
                ('substitute_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitutions_as_substitute', to='employees.employee', verbose_name='الموظف البديل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'تفويض مدير مؤقت',
                'verbose_name_plural': 'تفويضات المديرين المؤقتة',
                'ordering': ['-start_date'],
            },
        ),
    ]
