# Generated by Django 6.0.7 on 2026-08-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0010_managersubstitution'),
    ]

    operations = [
        migrations.AddField(
            model_name='managersubstitution',
            name='summary_viewed',
            field=models.BooleanField(default=False, verbose_name='شاف الملخص بعد الرجوع'),
        ),
    ]
