<<<<<<< HEAD
# Generated by Django 6.1 on 2026-08-23 11:06
=======
# Generated by Django 6.1 on 2026-08-23 14:33
>>>>>>> 15e61bffed7eefba4b18ba2198d5b4edbb7006e0

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0011_managersubstitution_summary_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='is_excused_absence',
            field=models.BooleanField(default=False, verbose_name='غياب بعذر'),
        ),
        migrations.AddField(
            model_name='leavetype',
            name='require_reason',
            field=models.BooleanField(default=False, verbose_name='السبب إجباري'),
        ),
    ]
