# Generated by Django 6.0.7 on 2026-07-08 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم الشركة بالعربي')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الشركة بالإنجليزي')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='companies/logos/', verbose_name='الشعار')),
                ('commercial_register', models.CharField(blank=True, max_length=50, null=True, verbose_name='السجل التجاري')),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='الرقم الضريبي')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('website', models.URLField(blank=True, null=True, verbose_name='الموقع الإلكتروني')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
            ],
            options={
                'verbose_name': 'شركة',
                'verbose_name_plural': 'الشركات',
                'ordering': ['name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم الفرع بالعربي')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الفرع بالإنجليزي')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول')),
                ('check_in_radius', models.IntegerField(default=100, verbose_name='نطاق تسجيل الحضور (متر)')),
                ('is_main', models.BooleanField(default=False, verbose_name='الفرع الرئيسي')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='companies.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['company', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم الإدارة بالعربي')),
                ('name_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم الإدارة بالإنجليزي')),
                ('code', models.CharField(blank=True, max_length=20, null=True, verbose_name='كود الإدارة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='companies.company', verbose_name='الشركة')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_departments', to='companies.department', verbose_name='الإدارة الأم')),
            ],
            options={
                'verbose_name': 'إدارة',
                'verbose_name_plural': 'الإدارات',
                'ordering': ['company', 'name_ar'],
            },
        ),
    ]
