# Generated by Django 6.0.7 on 2026-07-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_add_company_login_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyloginsettings',
            name='password_expiry_days',
            field=models.PositiveSmallIntegerField(default=0, help_text='0 = لا تنتهي', verbose_name='مدة انتهاء كلمة المرور (يوم)'),
        ),
    ]
