# Generated by Django 6.0.7 on 2026-07-10 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_alter_companyloginsettings_password_expiry_days'),
        ('employees', '0003_deduction'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ميثاق العمل', max_length=200, verbose_name='العنوان')),
                ('introduction', models.TextField(blank=True, help_text='نص تمهيدي يظهر قبل البنود', verbose_name='مقدمة')),
                ('content', models.TextField(help_text='البنود الكاملة للميثاق', verbose_name='محتوى الميثاق')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='رقم الإصدار')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعّل')),
                ('is_mandatory', models.BooleanField(default=True, verbose_name='إجباري للموظفين الجدد')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_charter', to='companies.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'ميثاق العمل',
                'verbose_name_plural': 'مواثيق العمل',
            },
        ),
        migrations.CreateModel(
            name='CharterAcceptance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الموافقة')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='عنوان IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='المتصفح')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charter_acceptances', to='employees.employee', verbose_name='الموظف')),
                ('charter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acceptances', to='companies.workcharter', verbose_name='الميثاق')),
            ],
            options={
                'verbose_name': 'موافقة على الميثاق',
                'verbose_name_plural': 'موافقات الميثاق',
                'unique_together': {('employee', 'charter')},
            },
        ),
    ]
