# Generated by Django 6.0.7 on 2026-07-10 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_workcharter_charteracceptance'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_period_minutes', models.PositiveSmallIntegerField(default=15, verbose_name='سماحية التأخير بالدقائق')),
                ('reset_late_counter_monthly', models.BooleanField(default=True, verbose_name='تصفير عداد التأخير شهريًا')),
                ('late_first_warning_after_count', models.PositiveSmallIntegerField(default=1, verbose_name='أول إنذار بعد عدد مرات')),
                ('late_second_warning_after_count', models.PositiveSmallIntegerField(default=2, verbose_name='ثاني إنذار بعد عدد مرات')),
                ('late_quarter_day_deduction_after_count', models.PositiveSmallIntegerField(default=3, verbose_name='خصم ربع يوم بعد عدد مرات')),
                ('late_half_day_deduction_after_count', models.PositiveSmallIntegerField(default=4, verbose_name='خصم نصف يوم بعد عدد مرات')),
                ('late_full_day_deduction_after_count', models.PositiveSmallIntegerField(default=5, verbose_name='خصم يوم كامل بعد عدد مرات')),
                ('permission_enabled', models.BooleanField(default=True, verbose_name='الأذونات مفعلة')),
                ('permission_monthly_limit', models.PositiveSmallIntegerField(default=2, verbose_name='عدد الأذونات المسموح بها شهريًا')),
                ('permission_max_hours_per_request', models.DecimalField(decimal_places=1, default=2, max_digits=4, verbose_name='أقصى عدد ساعات للإذن الواحد')),
                ('permission_requires_approval', models.BooleanField(default=True, verbose_name='الأذونات تحتاج موافقة')),
                ('overtime_enabled', models.BooleanField(default=True, verbose_name='الأوفر تايم مفعل')),
                ('overtime_start_after_minutes', models.PositiveSmallIntegerField(default=30, verbose_name='يبدأ الأوفر تايم بعد عدد دقائق')),
                ('overtime_requires_approval', models.BooleanField(default=True, verbose_name='الأوفر تايم يحتاج موافقة')),
                ('overtime_requires_reason', models.BooleanField(default=True, verbose_name='الموظف لازم يكتب سبب الأوفر تايم')),
                ('overtime_daily_max_hours', models.DecimalField(decimal_places=1, default=4, max_digits=4, verbose_name='أقصى أوفر تايم يومي')),
                ('overtime_monthly_max_hours', models.DecimalField(decimal_places=1, default=40, max_digits=5, verbose_name='أقصى أوفر تايم شهري')),
                ('checkin_requires_location', models.BooleanField(default=True, verbose_name='الحضور يحتاج موقع GPS')),
                ('checkin_requires_branch_range', models.BooleanField(default=True, verbose_name='الحضور لازم يكون داخل نطاق الفرع')),
                ('checkout_from_anywhere', models.BooleanField(default=True, verbose_name='الانصراف مسموح من أي مكان')),
                ('default_checkin_radius', models.PositiveSmallIntegerField(default=200, verbose_name='النطاق الافتراضي للحضور (متر)')),
                ('distance_tolerance_meters', models.PositiveSmallIntegerField(default=0, verbose_name='سماحية مسافة إضافية (متر)')),
                ('auto_absence_enabled', models.BooleanField(default=False, verbose_name='تفعيل الغياب التلقائي')),
                ('auto_absence_after_time', models.TimeField(blank=True, null=True, verbose_name='بعد الساعة يعتبر غياب')),
                ('hr_can_cancel_attendance', models.BooleanField(default=True, verbose_name='HR يقدر يلغي حضور/انصراف')),
                ('hr_can_edit_attendance', models.BooleanField(default=True, verbose_name='HR يقدر يعدل الحضور')),
                ('attendance_edit_reason_required', models.BooleanField(default=True, verbose_name='سبب التعديل إجباري')),
                ('manager_can_see_financial_requests', models.BooleanField(default=False, verbose_name='المدير يشوف الطلبات المالية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات إضافية')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='companies.company', verbose_name='الشركة')),
            ],
            options={
                'verbose_name': 'سياسات الشركة',
                'verbose_name_plural': 'سياسات الشركات',
            },
        ),
    ]
