# Generated by Django 6.0.7 on 2026-07-10 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_companypolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypolicy',
            name='employee_can_view_late_count',
            field=models.BooleanField(default=True, verbose_name='الموظف يشوف عدد تأخيراته'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='employee_can_view_warnings',
            field=models.BooleanField(default=True, verbose_name='الموظف يشوف إنذاراته'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='hr_override_reason_required',
            field=models.BooleanField(default=True, verbose_name='سبب إجباري لو HR تجاهل الإجراء'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='late_handling_mode',
            field=models.CharField(choices=[('monitor_only', 'مراقبة فقط'), ('recommendation_only', 'توصية + قرار HR'), ('auto_warn_manual_deduct', 'إنذارات تلقائية + خصومات بموافقة'), ('fully_automatic', 'تلقائي كامل')], default='recommendation_only', max_length=30, verbose_name='طريقة التعامل مع التأخير'),
        ),
    ]
