# Generated by Django 6.0.7 on 2026-07-10 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0006_companypolicy_employee_can_view_late_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypolicy',
            name='leave_day_checkin_mode',
            field=models.CharField(choices=[('block', 'منع تسجيل الحضور'), ('allow_notify_hr', 'سماح مع إشعار HR'), ('allow_convert_by_hr', 'سماح وHR يحول لتكليف')], default='block', max_length=25, verbose_name='لو الموظف سجل حضور يوم إجازته'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='off_day_checkin_mode',
            field=models.CharField(choices=[('block', 'منع تسجيل الحضور'), ('allow_notify_hr', 'سماح مع إشعار HR'), ('allow_convert_by_hr', 'سماح وHR يحول لتكليف')], default='allow_notify_hr', max_length=25, verbose_name='لو الموظف سجل حضور يوم راحته'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='unplanned_checkin_mode',
            field=models.CharField(choices=[('use_default', 'استخدم الإعداد الافتراضي'), ('create_exception', 'سجل كحالة استثنائية'), ('block', 'منع')], default='create_exception', max_length=25, verbose_name='لو مفيش تكليف ليومه'),
        ),
    ]
