# Generated by Django 6.0.7 on 2026-07-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0009_add_leave_substitute_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypolicy',
            name='stealth_tracking_alert_after_minutes',
            field=models.PositiveSmallIntegerField(default=15, verbose_name='تنبيه بعد عدد دقائق خارج النطاق'),
        ),
    ]
