# Generated by Django 6.0.7 on 2026-07-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0015_charter_digital_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='geofence_enabled',
            field=models.BooleanField(default=False, verbose_name='تفعيل التحقق من موقع الحضور'),
        ),
        migrations.AddField(
            model_name='company',
            name='geofence_radius',
            field=models.IntegerField(default=100, verbose_name='نطاق الشركة بالمتر'),
        ),
        migrations.AddField(
            model_name='company',
            name='office_address',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='عنوان الشركة النصي'),
        ),
        migrations.AddField(
            model_name='company',
            name='office_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط العرض للشركة'),
        ),
        migrations.AddField(
            model_name='company',
            name='office_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط الطول للشركة'),
        ),
    ]
