# Generated by Django 6.0.7 on 2026-07-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0016_company_geofence_enabled_company_geofence_radius_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='charter_files/', verbose_name='ملف مرفق (PDF/Word/صورة)'),
        ),
    ]
