# Generated by Django 6.0.7 on 2026-07-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0017_add_charter_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='attachment',
        ),
        migrations.AddField(
            model_name='workcharter',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='charter_files/', verbose_name='ملف مرفق (PDF/Word/صورة)'),
        ),
    ]
