# Generated by Django 6.0.7 on 2026-07-22 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customrole_rolepermission_userpermissionoverride_and_more'),
        ('companies', '0018_fix_charter_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='default_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='accounts.customrole', verbose_name='الدور الافتراضي'),
        ),
    ]
