# Generated by Django 6.0.7 on 2026-07-22 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_customrole_rolepermission_userpermissionoverride_and_more'),
        ('companies', '0019_branch_default_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='default_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_default_roles', to='accounts.customrole', verbose_name='الدور الافتراضي'),
        ),
        migrations.AlterField(
            model_name='branch',
            name='default_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branch_default_roles', to='accounts.customrole', verbose_name='الدور الافتراضي'),
        ),
    ]
