# Generated by Django 6.0.7 on 2026-07-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0020_department_default_role_alter_branch_default_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='payroll_cutoff_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='1-31، ويُستخدم فقط لو نوع الدورة cutoff_day', verbose_name='يوم قفل المرتب'),
        ),
        migrations.AddField(
            model_name='company',
            name='payroll_cycle_type',
            field=models.CharField(choices=[('calendar_month', 'الشهر الميلادي'), ('cutoff_day', 'يوم قفل ثابت')], default='calendar_month', help_text='calendar_month = من أول الشهر لآخره / cutoff_day = من يوم قفل ليوم القفل اللي بعده', max_length=20, verbose_name='نوع دورة المرتب'),
        ),
        migrations.AddField(
            model_name='company',
            name='payroll_pay_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='1-31', verbose_name='يوم صرف المرتب'),
        ),
        migrations.AddField(
            model_name='company',
            name='payroll_pay_month_offset',
            field=models.CharField(choices=[('same_month', 'نفس الشهر'), ('next_month', 'الشهر اللي بعده')], default='same_month', help_text='نفس الشهر أو الشهر اللي بعده', max_length=20, verbose_name='شهر صرف المرتب'),
        ),
        migrations.AddField(
            model_name='company',
            name='payroll_period_label_mode',
            field=models.CharField(choices=[('cutoff_month', 'شهر القفل'), ('pay_month', 'شهر الصرف'), ('custom', 'تسمية مخصصة')], default='cutoff_month', help_text='بتحدد اسم الدورة في التقارير والـ payroll runs', max_length=20, verbose_name='طريقة تسمية دورة المرتب'),
        ),
    ]
