# Generated by Django 6.0.7 on 2026-07-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0021_company_payroll_cutoff_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypolicy',
            name='tracking_interval_field_visit_minutes',
            field=models.PositiveSmallIntegerField(default=15, help_text='كل كام دقيقة يتم إرسال موقع الموظف أثناء الزيارة الميدانية النشطة', verbose_name='فترة التتبع أثناء الزيارة الميدانية (دقائق)'),
        ),
        migrations.AddField(
            model_name='companypolicy',
            name='tracking_interval_normal_minutes',
            field=models.PositiveSmallIntegerField(default=60, help_text='كل كام دقيقة يتم إرسال موقع الموظف أثناء الحضور العادي', verbose_name='فترة التتبع العادي (دقائق)'),
        ),
    ]
