# Generated by Django 6.0.7 on 2026-08-11 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0022_companypolicy_tracking_interval_field_visit_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dept_branch_link', to='companies.branch', verbose_name='الفرع'),
        ),
    ]
