# Generated by Django 6.0.7 on 2026-08-29 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0023_department_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='workcharter',
            name='target_branches',
            field=models.ManyToManyField(blank=True, related_name='work_charters', to='companies.branch', verbose_name='الفروع المستهدفة'),
        ),
        migrations.AddField(
            model_name='workcharter',
            name='target_departments',
            field=models.ManyToManyField(blank=True, related_name='work_charters', to='companies.department', verbose_name='الأقسام المستهدفة'),
        ),
        migrations.AddField(
            model_name='workcharter',
            name='target_roles',
            field=models.JSONField(blank=True, default=list, help_text='قائمة أدوار (زي manager, employee). فاضية = يستهدف الكل', verbose_name='الأدوار المستهدفة'),
        ),
        migrations.AlterField(
            model_name='workcharter',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_charters', to='companies.company', verbose_name='الشركة'),
        ),
    ]
