# Generated by Django 6.0.6 on 2026-07-09 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='مثال: continuous_tracking', max_length=100, unique=True, verbose_name='المفتاح')),
                ('name_ar', models.CharField(max_length=200, verbose_name='الاسم بالعربي')),
                ('name_en', models.CharField(max_length=200, verbose_name='الاسم بالإنجليزي')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('category', models.CharField(choices=[('core', 'أساسي'), ('attendance', 'الحضور'), ('tracking', 'التتبع'), ('leaves', 'الإجازات'), ('payroll', 'المرتبات'), ('reports', 'التقارير'), ('recruitment', 'التوظيف'), ('performance', 'الأداء'), ('training', 'التدريب'), ('advanced', 'متقدم')], default='core', max_length=20, verbose_name='التصنيف')),
                ('icon', models.CharField(default='bi-check-circle', max_length=50, verbose_name='الأيقونة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
            ],
            options={
                'verbose_name': 'ميزة',
                'verbose_name_plural': 'الميزات',
                'ordering': ['category', 'order', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربي')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزي')),
                ('tier', models.CharField(choices=[('trial', 'تجربة'), ('starter', 'Starter'), ('business', 'Business'), ('professional', 'Professional'), ('enterprise', 'Enterprise'), ('custom', 'مخصصة')], default='starter', max_length=20, verbose_name='المستوى')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('price_monthly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر الشهري')),
                ('price_yearly', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر السنوي')),
                ('max_employees', models.IntegerField(default=15, help_text='0 = غير محدود', verbose_name='حد الموظفين')),
                ('max_branches', models.IntegerField(default=1, help_text='0 = غير محدود', verbose_name='حد الفروع')),
                ('max_departments', models.IntegerField(default=5, help_text='0 = غير محدود', verbose_name='حد الإدارات')),
                ('is_trial', models.BooleanField(default=False, verbose_name='خطة تجريبية')),
                ('trial_days', models.IntegerField(default=14, verbose_name='أيام التجربة')),
                ('color', models.CharField(default='#06B6D4', max_length=20, verbose_name='اللون')),
                ('is_featured', models.BooleanField(default=False, verbose_name='مميزة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشطة')),
                ('order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('features', models.ManyToManyField(blank=True, related_name='plans', to='subscriptions.featureflag', verbose_name='الميزات المتاحة')),
            ],
            options={
                'verbose_name': 'خطة اشتراك',
                'verbose_name_plural': 'خطط الاشتراك',
                'ordering': ['order', 'price_monthly'],
            },
        ),
        migrations.CreateModel(
            name='CompanySubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ الانتهاء')),
                ('status', models.CharField(choices=[('active', 'نشط'), ('trial', 'تجربة'), ('expired', 'منتهي'), ('cancelled', 'ملغي'), ('suspended', 'موقوف'), ('grace_period', 'فترة سماح')], default='trial', max_length=20, verbose_name='الحالة')),
                ('billing_cycle', models.CharField(choices=[('trial', 'تجربة'), ('monthly', 'شهري'), ('quarterly', 'ربع سنوي'), ('semi_annual', 'نصف سنوي'), ('yearly', 'سنوي'), ('custom', 'مخصص'), ('lifetime', 'مدى الحياة')], default='trial', max_length=20, verbose_name='دورة الفوترة')),
                ('is_trial', models.BooleanField(default=False, verbose_name='تجربة')),
                ('trial_end_date', models.DateField(blank=True, null=True, verbose_name='نهاية التجربة')),
                ('grace_period_days', models.IntegerField(default=7, verbose_name='أيام فترة السماح')),
                ('custom_max_employees', models.IntegerField(blank=True, help_text='لو فارغ يستخدم حد الخطة', null=True, verbose_name='حد موظفين مخصص')),
                ('price_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='السعر المدفوع')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الخصم')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='companies.company', verbose_name='الشركة')),
                ('extra_features', models.ManyToManyField(blank=True, related_name='extra_subscriptions', to='subscriptions.featureflag', verbose_name='ميزات إضافية')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='subscriptions.subscriptionplan', verbose_name='الخطة')),
            ],
            options={
                'verbose_name': 'اشتراك شركة',
                'verbose_name_plural': 'اشتراكات الشركات',
                'ordering': ['-created_at'],
            },
        ),
    ]
