"""
Django settings for motionhr project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-+dz(2l3=@je*chaq0bhq)b5y&88$&-)uox73^n0k(=fa)2eb3$'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # MotionHR Apps
    'core',
    'accounts',
    'companies',
    'employees',   # ← جديد
    'attendance',
    'leaves',
    'reports',
    'requests_app',
    'landing',
    'subscriptions',
]   

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'core.middleware.CompanyPolicyStealthFinalSyncMiddleware',
    'core.middleware.CompanyPolicyStealthSyncMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    
    # MotionHR Middlewares
    'core.middleware.TenantMiddleware',
    'accounts.middleware.ForcePasswordChangeMiddleware',
    'core.middleware.CharterMiddleware',
    'core.middleware.CurrentEmployeeMiddleware',
    'core.middleware.SubscriptionMiddleware',
]

ROOT_URLCONF = 'motionhr.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'core.breadcrumb_processor.breadcrumb_processor',
                'core.breadcrumb_processor.vapid_key_processor',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'motionhr.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ar'
TIME_ZONE = 'Africa/Cairo'
USE_I18N = True
USE_TZ = True

# إعدادات إضافية
LANGUAGES = [
    ('ar', 'العربية'),
    ('en', 'English'),
]

# للتحكم في اتجاه الصفحة
LANGUAGE_BIDI = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
AUTH_USER_MODEL = 'accounts.User'
# Login/Logout Settings
LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/dashboard/'
LOGOUT_REDIRECT_URL = '/login/'


# Email Settings (للتطوير - يطبع في التيرمنال)
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DEFAULT_FROM_EMAIL = 'MotionHR <noreply@motionhr.com>'

# ─────────────────────────────────────────────
# بيانات التواصل للمبيعات (عدّلها بياناتك)
# ─────────────────────────────────────────────
MOTIONHR_SALES_CONTACT = {
    'company_name': 'MotionHR',
    'phone':        '01000000000',      # ← غيّر لرقمك
    'whatsapp':     '201000000000',     # ← غيّر لرقم الواتساب (بدون +)
    'email':        'sales@motionhr.com',  # ← غيّر لإيميلك
    'facebook':     '',
    'website':      '',
}

# ─────────────────────────────────────────────
# Authentication Backends
# ─────────────────────────────────────────────
AUTHENTICATION_BACKENDS = [
    'accounts.login_backend.SmartLoginBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# ─────────────────────────────────────────────
# Custom Error Pages
# ─────────────────────────────────────────────
# handler404 و handler500 بيتحددوا في urls.py

# ─────────────────────────────────────────────
# Web Push VAPID Keys
# ─────────────────────────────────────────────
# في الإنتاج: ولّد مفاتيح حقيقية بـ:
# pip install pywebpush
# python -c "from pywebpush import webpush; from py_vapid import Vapid; v=Vapid(); v.generate_keys(); print(v.public_key); print(v.private_key)"
VAPID_PUBLIC_KEY = "BDummyKeyForDevelopment_ReplaceInProduction_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
VAPID_PRIVATE_KEY = "dummyprivatekey_replace_in_production"
VAPID_ADMIN_EMAIL = "admin@motionhr.com"


# ═════════════════════════════════════════════════════════════
# Patch 50a — Production Deployment Overrides
# ═════════════════════════════════════════════════════════════
import os

# ── Environment helpers ─────────────────────────────────────
def _env_bool(name, default=False):
    value = os.getenv(name, str(default))
    return str(value).strip().lower() in ('1', 'true', 'yes', 'on')

def _env_list(name, default=''):
    value = os.getenv(name, default)
    return [item.strip() for item in str(value).split(',') if item.strip()]

# ── Core ────────────────────────────────────────────────────
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', SECRET_KEY)
DEBUG = _env_bool('DJANGO_DEBUG', DEBUG)

try:
    _default_hosts = ",".join(ALLOWED_HOSTS) if isinstance(ALLOWED_HOSTS, (list, tuple)) else str(ALLOWED_HOSTS)
except Exception:
    _default_hosts = ''
ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', _default_hosts or '127.0.0.1,localhost')

# CSRF trusted origins
_default_csrf = os.getenv('DJANGO_CSRF_TRUSTED_ORIGINS', '')
if _default_csrf:
    CSRF_TRUSTED_ORIGINS = _env_list('DJANGO_CSRF_TRUSTED_ORIGINS', _default_csrf)
else:
    try:
        if not DEBUG:
            CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS if host not in ['127.0.0.1', 'localhost']]
    except Exception:
        pass

# ── Database: PostgreSQL if env exists ──────────────────────
if os.getenv('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('POSTGRES_DB', ''),
            'USER': os.getenv('POSTGRES_USER', ''),
            'PASSWORD': os.getenv('POSTGRES_PASSWORD', ''),
            'HOST': os.getenv('POSTGRES_HOST', '127.0.0.1'),
            'PORT': os.getenv('POSTGRES_PORT', '5432'),
            'CONN_MAX_AGE': 60,
        }
    }

# ── Static / Media ──────────────────────────────────────────
STATIC_ROOT = BASE_DIR / 'staticfiles'
MEDIA_ROOT = BASE_DIR / 'media'

# ── Security for production behind Nginx ────────────────────
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = _env_bool('DJANGO_SECURE_SSL_REDIRECT', True)
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'SAMEORIGIN'
else:
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# ── Default admin contacts ──────────────────────────────────
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'info@jssolutions.com')
SERVER_EMAIL = os.getenv('SERVER_EMAIL', DEFAULT_FROM_EMAIL)

