# Generated by Django 6.0.7 on 2026-07-10 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
        ('companies', '0005_companypolicy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('action_type', models.CharField(choices=[('edit', 'تعديل'), ('cancel_checkin', 'إلغاء حضور'), ('cancel_checkout', 'إلغاء انصراف'), ('delete', 'حذف سجل')], max_length=20, verbose_name='نوع الإجراء')),
                ('reason', models.TextField(verbose_name='سبب التعديل')),
                ('old_data', models.JSONField(blank=True, default=dict, verbose_name='البيانات قبل التعديل')),
                ('new_data', models.JSONField(blank=True, default=dict, verbose_name='البيانات بعد التعديل')),
                ('action_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='attendance.attendance', verbose_name='سجل الحضور')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_actions', to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'سجل تعديل حضور',
                'verbose_name_plural': 'سجلات تعديلات الحضور',
                'ordering': ['-action_at'],
            },
        ),
    ]
