# Generated by Django 6.0.7 on 2026-07-10 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_attendanceactionlog'),
        ('companies', '0006_companypolicy_employee_can_view_late_count_and_more'),
        ('employees', '0003_deduction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LateNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('notification_type', models.CharField(choices=[('single_late', 'تأخير عادي'), ('threshold_reached', 'وصل الحد')], default='single_late', max_length=20, verbose_name='نوع الإشعار')),
                ('title', models.CharField(max_length=200, verbose_name='العنوان')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('details', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('suggested_action', models.CharField(blank=True, max_length=100, verbose_name='الإجراء المقترح')),
                ('incident_count', models.PositiveSmallIntegerField(default=1, verbose_name='عدد مرات التأخير')),
                ('month', models.PositiveSmallIntegerField(default=1, verbose_name='الشهر')),
                ('year', models.PositiveSmallIntegerField(default=2025, verbose_name='السنة')),
                ('is_read', models.BooleanField(default=False, verbose_name='تم القراءة')),
                ('is_acted_upon', models.BooleanField(default=False, verbose_name='تم اتخاذ إجراء')),
                ('action_taken', models.CharField(blank=True, max_length=50, verbose_name='الإجراء المتخذ')),
                ('action_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت الإجراء')),
                ('action_notes', models.TextField(blank=True, verbose_name='ملاحظات الإجراء')),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='late_actions_taken', to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_notifications', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'إشعار تأخير',
                'verbose_name_plural': 'إشعارات التأخير',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisciplinaryAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('action_type', models.CharField(choices=[('verbal_warning', 'إنذار شفهي'), ('written_warning', 'إنذار كتابي'), ('quarter_day_deduction', 'خصم ربع يوم'), ('half_day_deduction', 'خصم نصف يوم'), ('full_day_deduction', 'خصم يوم كامل'), ('suspension', 'إيقاف عن العمل'), ('termination_warning', 'إنذار فصل'), ('dismissed', 'تم الإعفاء / التجاهل')], max_length=30, verbose_name='نوع الإجراء')),
                ('reason', models.TextField(verbose_name='السبب')),
                ('auto_generated', models.BooleanField(default=False, verbose_name='تم تلقائيًا')),
                ('deduction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='مبلغ الخصم')),
                ('deduction_created', models.BooleanField(default=False, verbose_name='تم إنشاء خصم فعلي')),
                ('performed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإجراء')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_actions', to='employees.employee', verbose_name='الموظف')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_actions_performed', to=settings.AUTH_USER_MODEL, verbose_name='تم بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
                ('related_notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplinary_actions', to='attendance.latenotification', verbose_name='الإشعار المرتبط')),
            ],
            options={
                'verbose_name': 'إجراء تأديبي',
                'verbose_name_plural': 'الإجراءات التأديبية',
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='LateIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('late_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='دقائق التأخير')),
                ('shift_start_time', models.TimeField(blank=True, null=True, verbose_name='بداية الشيفت')),
                ('actual_checkin_time', models.TimeField(blank=True, null=True, verbose_name='وقت الحضور الفعلي')),
                ('grace_period_used', models.PositiveSmallIntegerField(default=0, verbose_name='السماحية المستخدمة')),
                ('month', models.PositiveSmallIntegerField(verbose_name='الشهر')),
                ('year', models.PositiveSmallIntegerField(verbose_name='السنة')),
                ('incident_number_in_month', models.PositiveSmallIntegerField(default=1, verbose_name='رقم الحادثة في الشهر')),
                ('is_excused', models.BooleanField(default=False, verbose_name='معذور')),
                ('excuse_reason', models.TextField(blank=True, verbose_name='سبب العذر')),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='late_incidents', to='attendance.attendance', verbose_name='سجل الحضور')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_incidents', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'حادثة تأخير',
                'verbose_name_plural': 'حوادث التأخير',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
