# Generated by Django 6.0.7 on 2026-07-10 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_latenotification_disciplinaryaction_lateincident'),
        ('companies', '0007_companypolicy_leave_day_checkin_mode_and_more'),
        ('employees', '0004_employee_attendance_mode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('day_type', models.CharField(choices=[('work_day', 'يوم عمل'), ('off_day', 'راحة أسبوعية'), ('leave_day', 'إجازة'), ('holiday', 'إجازة رسمية'), ('mission_day', 'مأمورية / مهمة'), ('standby_day', 'استدعاء / on-call'), ('training_day', 'يوم تدريب')], default='work_day', max_length=20, verbose_name='نوع اليوم')),
                ('work_mode', models.CharField(choices=[('fixed', 'ثابت'), ('flexible', 'مرن'), ('split', 'متقسم'), ('field', 'ميداني'), ('remote', 'عن بُعد'), ('mixed', 'مختلط')], default='fixed', max_length=20, verbose_name='طريقة التنفيذ')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='بداية العمل')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='نهاية العمل')),
                ('expected_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='الساعات المتوقعة')),
                ('segment_2_start', models.TimeField(blank=True, null=True, verbose_name='بداية الجزء الثاني')),
                ('segment_2_end', models.TimeField(blank=True, null=True, verbose_name='نهاية الجزء الثاني')),
                ('is_replacement', models.BooleanField(default=False, verbose_name='بديل لزميل')),
                ('is_extra_shift', models.BooleanField(default=False, verbose_name='شيفت إضافي')),
                ('count_as_overtime', models.BooleanField(default=False, verbose_name='يحسب أوفر تايم')),
                ('count_as_compensatory', models.BooleanField(default=False, verbose_name='يوم تعويضي')),
                ('requires_tracking', models.BooleanField(default=False, verbose_name='يحتاج تتبع GPS')),
                ('requires_visits', models.BooleanField(default=False, verbose_name='يحتاج تسجيل زيارات')),
                ('requires_geofence', models.BooleanField(default=True, verbose_name='يحتاج نطاق الفرع')),
                ('requires_manager_approval', models.BooleanField(default=False, verbose_name='يحتاج موافقة المدير مسبقاً')),
                ('task_title', models.CharField(blank=True, max_length=200, verbose_name='عنوان المهمة')),
                ('location_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الموقع')),
                ('status', models.CharField(choices=[('scheduled', 'مجدول'), ('in_progress', 'جاري'), ('completed', 'مكتمل'), ('cancelled', 'ملغي')], default='scheduled', max_length=20, verbose_name='الحالة')),
                ('is_exception', models.BooleanField(default=False, verbose_name='حالة استثنائية')),
                ('exception_reason', models.TextField(blank=True, verbose_name='سبب الاستثناء')),
                ('exception_status', models.CharField(blank=True, choices=[('pending_review', 'قيد المراجعة'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], max_length=20, verbose_name='حالة الاستثناء')),
                ('is_auto_generated', models.BooleanField(default=False, verbose_name='تم توليده تلقائياً')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_assignments', to=settings.AUTH_USER_MODEL, verbose_name='اعتمد بواسطة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_assignments', to='employees.employee', verbose_name='الموظف')),
                ('replaces_employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_assignments', to='employees.employee', verbose_name='بديل عن')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.shift', verbose_name='الشيفت')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'تكليف يومي',
                'verbose_name_plural': 'التكليفات اليومية',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
