# Generated by Django 6.0.7 on 2026-07-10 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_add_tracking_alert'),
        ('companies', '0010_alter_companypolicy_stealth_tracking_alert_after_minutes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingalert',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='وقت المعالجة'),
        ),
        migrations.AlterField(
            model_name='trackingalert',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة'),
        ),
        migrations.AlterField(
            model_name='trackingalert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='trackingalert',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة'),
        ),
        migrations.AlterField(
            model_name='trackingalert',
            name='last_address',
            field=models.TextField(blank=True, verbose_name='آخر عنوان'),
        ),
        migrations.AlterField(
            model_name='trackingalert',
            name='last_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='آخر خط عرض'),
        ),
        migrations.AlterField(
            model_name='trackingalert',
            name='last_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='آخر خط طول'),
        ),
        migrations.AlterField(
            model_name='trackingalert',
            name='minutes_outside',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='عدد الدقائق خارج النطاق'),
        ),
        migrations.AlterField(
            model_name='trackingalert',
            name='notes',
            field=models.TextField(blank=True, verbose_name='ملاحظات'),
        ),
        migrations.AlterField(
            model_name='trackingalert',
            name='notified_company_admin',
            field=models.BooleanField(default=False, verbose_name='تم تنبيه صاحب الشركة'),
        ),
        migrations.AlterField(
            model_name='trackingalert',
            name='notified_hr',
            field=models.BooleanField(default=False, verbose_name='تم تنبيه HR'),
        ),
        migrations.AlterField(
            model_name='trackingalert',
            name='notified_manager',
            field=models.BooleanField(default=False, verbose_name='تم تنبيه المدير'),
        ),
        migrations.AlterField(
            model_name='trackingalert',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_tracking_alerts', to=settings.AUTH_USER_MODEL, verbose_name='تمت المعالجة بواسطة'),
        ),
        migrations.AlterField(
            model_name='trackingalert',
            name='started_at',
            field=models.DateTimeField(verbose_name='وقت بداية الخروج من النطاق'),
        ),
        migrations.AlterField(
            model_name='trackingalert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='trackingalert',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة'),
        ),
    ]
