# Generated by Django 6.0.7 on 2026-07-18 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_trackingalert_resolved_at_and_more'),
        ('companies', '0018_fix_charter_attachment'),
        ('employees', '0009_employee_country'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط الطول')),
                ('accuracy', models.FloatField(blank=True, null=True, verbose_name='الدقة')),
                ('recorded_at', models.DateTimeField(verbose_name='وقت التسجيل')),
                ('shift_date', models.DateField(verbose_name='تاريخ الشيفت')),
                ('point_index', models.IntegerField(default=0, verbose_name='رقم النقطة')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='العنوان')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_history', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'سجل موقع',
                'verbose_name_plural': 'سجلات المواقع',
                'ordering': ['shift_date', 'recorded_at'],
            },
        ),
    ]
