# Generated by Django 6.0.7 on 2026-07-18 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_add_location_history'),
        ('companies', '0018_fix_charter_attachment'),
        ('employees', '0010_add_currency_to_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان المهمة')),
                ('description', models.TextField(blank=True, verbose_name='تفاصيل المهمة')),
                ('priority', models.CharField(choices=[('urgent', 'عاجل'), ('high', 'عالي'), ('normal', 'عادي')], default='normal', max_length=20)),
                ('planned_start_time', models.DateTimeField(verbose_name='وقت البدء المخطط')),
                ('planned_end_time', models.DateTimeField(verbose_name='وقت الانتهاء المخطط')),
                ('location_name', models.CharField(blank=True, max_length=500, verbose_name='اسم الموقع')),
                ('location_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('client_name', models.CharField(blank=True, max_length=255, verbose_name='اسم العميل')),
                ('client_phone', models.CharField(blank=True, max_length=50, verbose_name='تليفون العميل')),
                ('source', models.CharField(choices=[('manager', 'من المدير'), ('employee_request', 'طلب موظف')], default='manager', max_length=30)),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('pending_approval', 'في انتظار الموافقة'), ('approved', 'معتمدة'), ('in_progress', 'جارية'), ('completed', 'مكتملة'), ('cancelled', 'ملغية')], default='approved', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_missions', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'مهمة',
                'verbose_name_plural': 'المهمات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('role_in_mission', models.CharField(choices=[('lead', 'قائد المهمة'), ('assistant', 'مساعد'), ('manager', 'مدير مرافق'), ('trainee', 'متدرب')], default='lead', max_length=20)),
                ('is_lead', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('accepted', 'قبل'), ('rejected', 'رفض'), ('in_progress', 'جارية'), ('completed', 'مكتملة')], default='pending', max_length=20)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('start_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('start_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('end_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_assignments', to='employees.employee')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='attendance.mission')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'تعيين مهمة',
                'verbose_name_plural': 'تعيينات المهمات',
                'unique_together': {('mission', 'employee')},
            },
        ),
        migrations.CreateModel(
            name='MissionAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='missions/attachments/%Y/%m/')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='attendance.missionassignment')),
            ],
            options={
                'verbose_name': 'مرفق مهمة',
            },
        ),
        migrations.CreateModel(
            name='MissionClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('actual_address', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_info', to='attendance.mission')),
            ],
            options={
                'verbose_name': 'بيانات عميل المهمة',
            },
        ),
        migrations.CreateModel(
            name='MissionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('written_at', models.DateTimeField(auto_now_add=True)),
                ('interest_rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
                ('deal_probability', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
                ('client_status', models.CharField(choices=[('very_interested', 'مهتم جداً'), ('interested', 'مهتم'), ('thinking', 'يفكر'), ('not_interested', 'غير مهتم'), ('postponed', 'مؤجل')], default='thinking', max_length=30)),
                ('client_needs', models.TextField(blank=True)),
                ('estimated_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('expected_decision_date', models.DateField(blank=True, null=True)),
                ('interested_in', models.TextField(blank=True)),
                ('needs_followup', models.BooleanField(default=False)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('preferred_contact', models.CharField(blank=True, choices=[('phone', 'تليفون'), ('whatsapp', 'واتساب'), ('email', 'إيميل'), ('visit', 'زيارة')], max_length=20)),
                ('followup_notes', models.TextField(blank=True)),
                ('contract_signed', models.BooleanField(default=False)),
                ('deal_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('followup_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_followups', to='employees.employee')),
                ('mission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='attendance.mission')),
                ('written_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_feedbacks', to='employees.employee')),
            ],
            options={
                'verbose_name': 'فيدباك المهمة',
            },
        ),
        migrations.CreateModel(
            name='MissionFeedbackAddendum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addenda', to='attendance.missionfeedback')),
            ],
            options={
                'verbose_name': 'ملاحظة إضافية على الفيدباك',
            },
        ),
        migrations.CreateModel(
            name='MissionFollowup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('scheduled', 'مجدول'), ('done', 'تم'), ('cancelled', 'ملغي')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.employee')),
                ('followup_mission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_from_followup', to='attendance.mission')),
                ('original_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='attendance.mission')),
            ],
            options={
                'verbose_name': 'متابعة مهمة',
                'verbose_name_plural': 'متابعات المهمات',
            },
        ),
        migrations.CreateModel(
            name='MissionLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_label', models.CharField(blank=True, max_length=255, verbose_name='وصف الموقع')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('added_by_employee', models.BooleanField(default=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='attendance.missionassignment')),
            ],
            options={
                'verbose_name': 'موقع مهمة',
                'ordering': ['recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='MissionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_approval', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'موافق'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('manager_responded_at', models.DateTimeField(blank=True, null=True)),
                ('manager_notes', models.TextField(blank=True)),
                ('hr_notified_at', models.DateTimeField(blank=True, null=True)),
                ('final_status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'موافق'), ('rejected', 'مرفوض')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_approvals', to=settings.AUTH_USER_MODEL)),
                ('mission', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mission_request', to='attendance.mission')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mission_requests', to='employees.employee')),
            ],
            options={
                'verbose_name': 'طلب مهمة',
                'verbose_name_plural': 'طلبات المهمات',
            },
        ),
    ]
