# Generated by Django 6.0.7 on 2026-07-20 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_missions_v1'),
        ('companies', '0018_fix_charter_attachment'),
        ('employees', '0010_add_currency_to_employee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWorkPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('work_sunday', models.BooleanField(default=True, verbose_name='الأحد')),
                ('work_monday', models.BooleanField(default=True, verbose_name='الاثنين')),
                ('work_tuesday', models.BooleanField(default=True, verbose_name='الثلاثاء')),
                ('work_wednesday', models.BooleanField(default=True, verbose_name='الأربعاء')),
                ('work_thursday', models.BooleanField(default=True, verbose_name='الخميس')),
                ('work_friday', models.BooleanField(default=False, verbose_name='الجمعة')),
                ('work_saturday', models.BooleanField(default=False, verbose_name='السبت')),
                ('is_24_7', models.BooleanField(default=False, help_text='الإجازات بالتناوب بدون يوم ثابت', verbose_name='عمل 24/7')),
                ('rotation_type', models.CharField(choices=[('none', 'بدون تناوب'), ('weekly', 'تناوب أسبوعي'), ('monthly', 'تناوب شهري')], default='none', max_length=10, verbose_name='نوع التناوب')),
                ('late_deduction_per_minute', models.DecimalField(decimal_places=2, default=1.0, max_digits=6, verbose_name='خصم التأخير / دقيقة')),
                ('absence_deduction_per_day', models.DecimalField(decimal_places=2, default=200.0, max_digits=8, verbose_name='خصم الغياب / يوم')),
                ('overtime_rate_per_hour', models.DecimalField(decimal_places=2, default=50.0, max_digits=6, verbose_name='معدل Overtime / ساعة')),
                ('auto_checkin_enabled', models.BooleanField(default=False, verbose_name='تسجيل حضور أوتوماتيك')),
                ('auto_checkout_enabled', models.BooleanField(default=False, verbose_name='تسجيل انصراف أوتوماتيك')),
                ('auto_checkin_radius', models.IntegerField(default=100, verbose_name='نطاق الحضور الأوتوماتيك (متر)')),
                ('auto_checkout_grace', models.IntegerField(default=30, verbose_name='وقت السماح بعد الشيفت (دقيقة)')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_policy', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'سياسة عمل الشركة',
                'verbose_name_plural': 'سياسات عمل الشركات',
            },
        ),
        migrations.CreateModel(
            name='PayrollAllowance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('allowance_type', models.CharField(choices=[('transport', 'بدل مواصلات'), ('housing', 'بدل سكن'), ('phone', 'بدل هاتف'), ('meal', 'بدل وجبة'), ('performance', 'علاوة أداء'), ('other', 'أخرى')], max_length=20, verbose_name='نوع البدل')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربي')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزي')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('is_monthly', models.BooleanField(default=True, verbose_name='شهري')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='لحد تاريخ')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowances', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'بدل',
                'verbose_name_plural': 'البدلات',
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('deduction_type', models.CharField(choices=[('social_insurance', 'تأمينات اجتماعية'), ('tax', 'ضريبة'), ('loan', 'سلفة'), ('installment', 'قسط'), ('penalty', 'جزاء'), ('other', 'أخرى')], max_length=20, verbose_name='نوع الخصم')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربي')),
                ('name_en', models.CharField(blank=True, max_length=100, verbose_name='الاسم بالإنجليزي')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('is_monthly', models.BooleanField(default=True, verbose_name='شهري')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='لحد تاريخ')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_deductions', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'خصم إضافي',
                'verbose_name_plural': 'الخصومات الإضافية',
            },
        ),
    ]
