# Generated by Django 6.0.7 on 2026-07-20 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0009_phase14_company_policy'),
        ('companies', '0018_fix_charter_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('late_deduction_per_minute', models.DecimalField(decimal_places=2, default=1.0, max_digits=8, verbose_name='خصم التأخير (لكل دقيقة)')),
                ('absence_deduction_per_day', models.DecimalField(decimal_places=2, default=200.0, max_digits=8, verbose_name='خصم الغياب (لكل يوم)')),
                ('overtime_rate_per_hour', models.DecimalField(decimal_places=2, default=50.0, max_digits=8, verbose_name='بدل العمل الإضافي (لكل ساعة)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payroll_settings', to='companies.company')),
            ],
            options={
                'verbose_name': 'إعدادات الرواتب',
                'verbose_name_plural': 'إعدادات الرواتب',
            },
        ),
    ]
