# Generated by Django 6.0.7 on 2026-07-21 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_payroll_pro'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='insurance_fixed_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='مبلغ التأمين الثابت'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='insurance_mode',
            field=models.CharField(choices=[('none', 'بدون'), ('fixed', 'مبلغ ثابت'), ('percent', 'نسبة من الأساسي')], default='none', max_length=10, verbose_name='طريقة حساب التأمينات'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='insurance_percent',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='نسبة التأمين من الأساسي'),
        ),
    ]
