# Generated by Django 6.0.7 on 2026-07-23 16:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_payroll_settings_insurance'),
        ('companies', '0020_department_default_role_alter_branch_default_role'),
        ('employees', '0011_employee_instapay_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeshift',
            name='assignment_type',
            field=models.CharField(choices=[('company', 'شركة'), ('branch', 'فرع'), ('department', 'قسم'), ('employee', 'موظف')], default='employee', max_length=20, verbose_name='نوع التعيين'),
        ),
        migrations.AddField(
            model_name='employeeshift',
            name='priority',
            field=models.IntegerField(default=1, help_text='1=موظف, 2=قسم, 3=فرع, 4=شركة', verbose_name='الأولوية'),
        ),
        migrations.AddField(
            model_name='shift',
            name='crosses_midnight',
            field=models.BooleanField(default=False, help_text='فعّل لو الشيفت بيبدأ بالليل وبينتهي الصبح', verbose_name='يمتد لليوم التالي'),
        ),
        migrations.AddField(
            model_name='shift',
            name='early_checkin_minutes',
            field=models.IntegerField(default=30, help_text='الحد الأقصى المسموح لتسجيل الحضور قبل بداية الشيفت', verbose_name='مسموح الحضور قبل الشيفت (دقيقة)'),
        ),
        migrations.AddField(
            model_name='shift',
            name='grace_early_leave',
            field=models.IntegerField(default=0, help_text='الوقت المسموح للانصراف قبل نهاية الشيفت بدون احتساب انصراف مبكر', verbose_name='فترة السماح للانصراف المبكر (دقيقة)'),
        ),
        migrations.AddField(
            model_name='shift',
            name='is_default',
            field=models.BooleanField(default=False, help_text='لو مفيش شيفت محدد للموظف، هيستخدم الشيفت الافتراضي', verbose_name='شيفت افتراضي للشركة'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='grace_period',
            field=models.IntegerField(default=15, help_text='الوقت المسموح للتأخير بدون احتساب تأخير', verbose_name='فترة السماح للتأخير (دقيقة)'),
        ),
        migrations.AlterField(
            model_name='shift',
            name='shift_type',
            field=models.CharField(choices=[('fixed', 'ثابت'), ('flexible', 'مرن'), ('rotating', 'متغير'), ('morning', 'صباحي'), ('evening', 'مسائي'), ('night', 'ليلي'), ('split', 'مقسم')], default='fixed', max_length=20, verbose_name='نوع الشيفت'),
        ),
        migrations.CreateModel(
            name='ShiftChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('effective_from', models.DateField(verbose_name='تاريخ بداية السريان')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='تاريخ نهاية السريان')),
                ('status', models.CharField(choices=[('pending', 'في الانتظار'), ('approved', 'موافق عليه'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='يحتاج موافقة')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='سبب الرفض')),
                ('reason', models.TextField(blank=True, verbose_name='سبب طلب التغيير')),
                ('notified_manager', models.BooleanField(default=False, verbose_name='تم إبلاغ المدير')),
                ('notified_hr', models.BooleanField(default=False, verbose_name='تم إبلاغ HR')),
                ('notified_employee', models.BooleanField(default=False, verbose_name='تم إبلاغ الموظف')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_changes_approved', to=settings.AUTH_USER_MODEL, verbose_name='وافق بواسطة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_change_requests', to='employees.employee', verbose_name='الموظف')),
                ('new_shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='new_change_requests', to='attendance.shift', verbose_name='الشيفت الجديد')),
                ('old_shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_change_requests', to='attendance.shift', verbose_name='الشيفت القديم')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shift_changes_requested', to=settings.AUTH_USER_MODEL, verbose_name='طلب بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'طلب تغيير شيفت',
                'verbose_name_plural': 'طلبات تغيير الشيفتات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('name', models.CharField(max_length=100, verbose_name='اسم التناوب')),
                ('rotation_type', models.CharField(choices=[('weekly', 'أسبوعي'), ('biweekly', 'كل أسبوعين'), ('monthly', 'شهري')], default='weekly', max_length=20, verbose_name='نوع التناوب')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية التناوب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employees', models.ManyToManyField(related_name='rotations', to='employees.employee', verbose_name='الموظفون')),
                ('shifts', models.ManyToManyField(related_name='rotations', to='attendance.shift', verbose_name='الشيفتات')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'تناوب شيفتات',
                'verbose_name_plural': 'تناوبات الشيفتات',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ShiftOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('override_date', models.DateField(verbose_name='تاريخ الاستثناء')),
                ('reason', models.TextField(blank=True, verbose_name='سبب الاستثناء')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_overrides', to='employees.employee', verbose_name='الموظف')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='overrides', to='attendance.shift', verbose_name='الشيفت البديل')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'استثناء شيفت',
                'verbose_name_plural': 'استثناءات الشيفتات',
                'ordering': ['-override_date'],
                'unique_together': {('employee', 'override_date')},
            },
        ),
    ]
