# Generated by Django 6.0.7 on 2026-07-23 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_employeeshift_assignment_type_employeeshift_priority_and_more'),
        ('companies', '0020_department_default_role_alter_branch_default_role'),
        ('employees', '0011_employee_instapay_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShiftAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('assignment_type', models.CharField(choices=[('company', 'شركة'), ('branch', 'فرع'), ('department', 'قسم'), ('employee', 'موظف')], max_length=20, verbose_name='نوع التعيين')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('priority', models.IntegerField(default=4, help_text='1=موظف, 2=قسم, 3=فرع, 4=شركة', verbose_name='الأولوية')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='companies.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='companies.department', verbose_name='القسم')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='employees.employee', verbose_name='الموظف')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='attendance.shift', verbose_name='الشيفت')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'تعيين شيفت',
                'verbose_name_plural': 'تعيينات الشيفتات',
                'ordering': ['priority', '-start_date'],
            },
        ),
    ]
