# Generated by Django 6.0.7 on 2026-07-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_shiftassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='allow_partial_checkout',
            field=models.BooleanField(default=False, help_text='مطلوب للمرن المقسم والمقسم الثابت', verbose_name='يسمح بخروج جزئي'),
        ),
        migrations.AddField(
            model_name='shift',
            name='max_sessions_per_day',
            field=models.PositiveSmallIntegerField(default=1, help_text='مثلاً 2 للمرن المقسم أو المقسم الثابت', verbose_name='أقصى عدد فترات في اليوم'),
        ),
        migrations.AddField(
            model_name='shift',
            name='required_daily_hours',
            field=models.DecimalField(decimal_places=2, default=8, help_text='مهم للمرن الثابت والمرن المقسم', max_digits=5, verbose_name='عدد الساعات المطلوبة يوميًا'),
        ),
        migrations.AddField(
            model_name='shift',
            name='schedule_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='إعدادات الجدول الديناميكي'),
        ),
        migrations.AddField(
            model_name='shift',
            name='shift_mode',
            field=models.CharField(choices=[('fixed', 'ثابت'), ('flex_fixed', 'مرن ثابت'), ('flex_split', 'مرن مقسم'), ('variable_daily', 'متغير يومي'), ('variable_weekly', 'متغير أسبوعي'), ('variable_weekly_flex', 'متغير أسبوعي مرن'), ('split_fixed', 'مقسم ثابت')], default='fixed', help_text='بيحدد منطق الشيفت: ثابت، مرن، متغير، مقسم...', max_length=30, verbose_name='النمط السلوكي للشيفت'),
        ),
        migrations.AddField(
            model_name='shift',
            name='time_preset',
            field=models.CharField(choices=[('custom', 'مخصص'), ('morning', 'صباحي'), ('evening', 'مسائي'), ('night', 'ليلي')], default='custom', help_text='للواجهة فقط: صباحي / مسائي / ليلي / مخصص', max_length=20, verbose_name='توقيت افتراضي'),
        ),
        migrations.AddField(
            model_name='shift',
            name='variable_schedule_type',
            field=models.CharField(choices=[('none', 'لا يوجد'), ('daily', 'يومي'), ('weekly', 'أسبوعي'), ('weekly_flex', 'أسبوعي مرن')], default='none', max_length=20, verbose_name='نوع الجدول المتغير'),
        ),
    ]
