# Generated by Django 6.0.7 on 2026-07-24 00:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0015_shift_allow_partial_checkout_and_more'),
        ('companies', '0020_department_default_role_alter_branch_default_role'),
        ('employees', '0011_employee_instapay_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('session_number', models.PositiveSmallIntegerField(default=1, help_text='1 للفترة الأولى، 2 للثانية...', verbose_name='رقم الفترة')),
                ('check_in_time', models.DateTimeField(verbose_name='وقت دخول الفترة')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='وقت خروج الفترة')),
                ('check_in_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط عرض الدخول')),
                ('check_in_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط طول الدخول')),
                ('check_out_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط عرض الخروج')),
                ('check_out_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='خط طول الخروج')),
                ('is_partial', models.BooleanField(default=False, help_text='True لو الموظف خرج ورجع تاني', verbose_name='خروج جزئي')),
                ('worked_minutes', models.IntegerField(default=0, verbose_name='دقائق العمل في الفترة دي')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='attendance.attendance', verbose_name='سجل الحضور')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'فترة حضور',
                'verbose_name_plural': 'فترات الحضور',
                'ordering': ['attendance', 'session_number'],
                'unique_together': {('attendance', 'session_number')},
            },
        ),
    ]
