# Generated by Django 6.0.7 on 2026-07-24 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0016_attendancesession'),
        ('companies', '0020_department_default_role_alter_branch_default_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('name', models.CharField(max_length=200, verbose_name='اسم السياسة')),
                ('effective_from', models.DateField(verbose_name='سارية من')),
                ('effective_to', models.DateField(blank=True, null=True, verbose_name='سارية لحد')),
                ('status', models.CharField(choices=[('draft', 'مسودة'), ('approved', 'معتمد'), ('active', 'نشط'), ('archived', 'مؤرشف')], default='draft', max_length=20, verbose_name='الحالة')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_policies', to=settings.AUTH_USER_MODEL, verbose_name='وافق بواسطة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'سياسة حضور',
                'verbose_name_plural': 'سياسات الحضور',
                'ordering': ['-effective_from'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_type', models.CharField(choices=[('unexcused', 'بدون إذن'), ('consecutive', 'متتالي'), ('repeated', 'متكرر في الشهر')], default='unexcused', max_length=20, verbose_name='نوع الغياب')),
                ('consecutive_days', models.IntegerField(blank=True, default=1, null=True, verbose_name='عدد الأيام المتتالية')),
                ('occurrences_in_month', models.IntegerField(blank=True, default=1, null=True, verbose_name='عدد المرات في الشهر')),
                ('deduction_type', models.CharField(choices=[('day_fraction', 'نسبة من اليوم'), ('fixed_amount', 'مبلغ ثابت'), ('warning', 'إنذار فقط')], default='day_fraction', max_length=20, verbose_name='نوع الخصم')),
                ('deduction_value', models.DecimalField(decimal_places=4, default=1, help_text='1 = يوم كامل / 1.5 = يوم ونص / 50 = مبلغ ثابت', max_digits=8, verbose_name='قيمة الخصم')),
                ('display_order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_rules', to='attendance.attendancepolicy', verbose_name='السياسة')),
            ],
            options={
                'verbose_name': 'قاعدة غياب',
                'verbose_name_plural': 'قواعد الغياب',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='AttendancePolicyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('assignment_type', models.CharField(choices=[('company', 'شركة'), ('branch', 'فرع'), ('department', 'قسم')], default='company', max_length=20, verbose_name='نوع التعيين')),
                ('priority', models.IntegerField(default=3, help_text='1=قسم, 2=فرع, 3=شركة', verbose_name='الأولوية')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.department', verbose_name='القسم')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='attendance.attendancepolicy', verbose_name='السياسة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'تعيين سياسة',
                'verbose_name_plural': 'تعيينات السياسات',
            },
        ),
        migrations.CreateModel(
            name='LateRepeatPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrences', models.IntegerField(default=3, verbose_name='عدد مرات التأخير في الشهر')),
                ('penalty_type', models.CharField(choices=[('warning', 'إنذار'), ('deduction', 'خصم'), ('suspension', 'وقف')], default='warning', max_length=20, verbose_name='نوع الجزاء')),
                ('deduction_value', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='قيمة الخصم')),
                ('description', models.TextField(blank=True, verbose_name='وصف الجزاء')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_repeat_penalties', to='attendance.attendancepolicy', verbose_name='السياسة')),
            ],
            options={
                'verbose_name': 'جزاء تكرار التأخير',
                'verbose_name_plural': 'جزاءات تكرار التأخير',
                'ordering': ['occurrences'],
            },
        ),
        migrations.CreateModel(
            name='LateRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_minutes', models.IntegerField(default=0, verbose_name='من دقيقة')),
                ('to_minutes', models.IntegerField(default=15, verbose_name='إلى دقيقة')),
                ('deduction_type', models.CharField(choices=[('none', 'لا خصم'), ('day_fraction', 'نسبة من اليوم'), ('fixed_amount', 'مبلغ ثابت'), ('per_minute', 'لكل دقيقة')], default='none', max_length=20, verbose_name='نوع الخصم')),
                ('deduction_value', models.DecimalField(decimal_places=4, default=0, help_text='0.25 = ربع يوم / 50 = مبلغ ثابت / 1 = لكل دقيقة', max_digits=8, verbose_name='قيمة الخصم')),
                ('display_order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_rules', to='attendance.attendancepolicy', verbose_name='السياسة')),
            ],
            options={
                'verbose_name': 'قاعدة تأخير',
                'verbose_name_plural': 'قواعد التأخير',
                'ordering': ['display_order', 'from_minutes'],
            },
        ),
        migrations.CreateModel(
            name='NightShiftRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowance_type', models.CharField(choices=[('fixed_amount', 'مبلغ ثابت'), ('percentage', 'نسبة من اليومي')], default='fixed_amount', max_length=20, verbose_name='نوع البدل')),
                ('amount', models.DecimalField(decimal_places=2, default=50, max_digits=10, verbose_name='المبلغ الثابت')),
                ('percentage', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='النسبة المئوية من الأجر اليومي')),
                ('night_start_hour', models.IntegerField(default=20, help_text='20 = 8 مساءً', verbose_name='بداية الليل (ساعة)')),
                ('min_night_hours', models.IntegerField(default=4, verbose_name='أقل ساعات ليلية للاستحقاق')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='night_shift_rules', to='attendance.attendancepolicy', verbose_name='السياسة')),
            ],
            options={
                'verbose_name': 'قاعدة بدل ليلي',
                'verbose_name_plural': 'قواعد البدل الليلي',
            },
        ),
        migrations.CreateModel(
            name='OvertimeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overtime_type', models.CharField(choices=[('regular', 'عادي'), ('after_shift', 'بعد الشيفت'), ('weekend', 'يوم راحة'), ('holiday', 'إجازة رسمية')], default='after_shift', max_length=20, verbose_name='نوع الأوفر تايم')),
                ('multiplier', models.DecimalField(decimal_places=2, default=1.5, help_text='1.5 = مرة ونص / 2.0 = ضعفين', max_digits=4, verbose_name='المضاعف')),
                ('min_minutes', models.IntegerField(default=30, verbose_name='أقل وقت يتحسب (دقيقة)')),
                ('max_hours_per_day', models.IntegerField(blank=True, default=4, null=True, verbose_name='أقصى ساعات في اليوم')),
                ('max_hours_per_month', models.IntegerField(blank=True, default=40, null=True, verbose_name='أقصى ساعات في الشهر')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='يحتاج موافقة مسبقة')),
                ('display_order', models.IntegerField(default=0, verbose_name='الترتيب')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overtime_rules', to='attendance.attendancepolicy', verbose_name='السياسة')),
            ],
            options={
                'verbose_name': 'قاعدة أوفر تايم',
                'verbose_name_plural': 'قواعد الأوفر تايم',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='WeekendWorkRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compensation_type', models.CharField(choices=[('overtime_multiplier', 'نسبة من المرتب'), ('fixed_amount', 'مبلغ ثابت'), ('day_off', 'يوم إجازة بديل')], default='overtime_multiplier', max_length=30, verbose_name='نوع التعويض')),
                ('multiplier', models.DecimalField(decimal_places=2, default=2.0, max_digits=4, verbose_name='المضاعف')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='المبلغ الثابت')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekend_work_rules', to='attendance.attendancepolicy', verbose_name='السياسة')),
            ],
            options={
                'verbose_name': 'قاعدة عمل يوم الراحة',
                'verbose_name_plural': 'قواعد العمل يوم الراحة',
            },
        ),
    ]
