# Generated by Django 6.0.7 on 2026-07-24 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_attendancepolicy_absencerule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='permission_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='permission_fraction_as_full',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='permission_max_hours_per_request',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='permission_monthly_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='permission_monthly_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='permission_reset_cycle',
            field=models.CharField(choices=[('calendar', 'شهر ميلادي'), ('payroll', 'دورة المرتب')], default='calendar', max_length=20),
        ),
    ]
