# Generated by Django 6.0.7 on 2026-07-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_permissionledger'),
        ('employees', '0011_employee_instapay_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftassignment',
            name='excluded_employees',
            field=models.ManyToManyField(blank=True, related_name='excluded_from_shift_assignments', to='employees.employee', verbose_name='الموظفون المستثنون'),
        ),
    ]
