# Generated by Django 6.0.7 on 2026-07-24 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0020_shiftassignment_excluded_employees'),
        ('companies', '0020_department_default_role_alter_branch_default_role'),
        ('employees', '0011_employee_instapay_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shiftrotation',
            name='employees',
        ),
        migrations.RemoveField(
            model_name='shiftrotation',
            name='rotation_type',
        ),
        migrations.RemoveField(
            model_name='shiftrotation',
            name='shifts',
        ),
        migrations.AddField(
            model_name='shiftrotation',
            name='cycle_length_days',
            field=models.PositiveSmallIntegerField(default=7, verbose_name='طول الدورة (أيام)'),
        ),
        migrations.AlterField(
            model_name='shiftrotation',
            name='start_date',
            field=models.DateField(verbose_name='تاريخ بداية التناوب المرجعي'),
        ),
        migrations.CreateModel(
            name='ShiftRotationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('assignment_type', models.CharField(choices=[('company', 'شركة'), ('branch', 'فرع'), ('department', 'قسم'), ('employee', 'موظف')], max_length=20, verbose_name='نوع التعيين')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاريخ النهاية')),
                ('priority', models.IntegerField(default=4, help_text='1=موظف, 2=قسم, 3=فرع, 4=شركة', verbose_name='الأولوية')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.department', verbose_name='القسم')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employees.employee', verbose_name='الموظف')),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='attendance.shiftrotation', verbose_name='التناوب')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'ordering': ['priority', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ShiftRotationSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('start_day_index', models.PositiveSmallIntegerField(help_text='0 = أول يوم في الدورة', verbose_name='من يوم رقم')),
                ('end_day_index', models.PositiveSmallIntegerField(verbose_name='إلى يوم رقم')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('rotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='attendance.shiftrotation', verbose_name='التناوب')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotation_slots', to='attendance.shift', verbose_name='الشيفت (فارغ = إجازة)')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'ordering': ['start_day_index'],
            },
        ),
    ]
