# Generated by Django 6.0.7 on 2026-07-25 03:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0021_remove_shiftrotation_employees_and_more'),
        ('companies', '0020_department_default_role_alter_branch_default_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='shift',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('company',), name='uniq_default_shift_per_company'),
        ),
    ]
