# Generated by Django 6.0.7 on 2026-07-25 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0022_shift_uniq_default_shift_per_company'),
        ('companies', '0021_company_payroll_cutoff_day_and_more'),
        ('employees', '0011_employee_instapay_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendanceSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('on_leave', 'في إجازة'), ('weekend', 'إجازة أسبوعية'), ('mission', 'مأمورية'), ('holiday', 'عطلة رسمية')], default='absent', max_length=20, verbose_name='الحالة')),
                ('effective_status', models.CharField(choices=[('present', 'حاضر'), ('absent', 'غائب'), ('late', 'متأخر'), ('on_leave', 'في إجازة'), ('weekend', 'إجازة أسبوعية'), ('mission', 'مأمورية'), ('holiday', 'عطلة رسمية')], default='absent', max_length=20, verbose_name='الحالة الفعلية (بعد الأذونات)')),
                ('late_minutes', models.IntegerField(default=0, verbose_name='دقائق التأخير')),
                ('work_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ساعات العمل')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ساعات الأوفرتايم')),
                ('is_night_shift', models.BooleanField(default=False, verbose_name='شيفت ليلي')),
                ('is_weekend_work', models.BooleanField(default=False, verbose_name='عمل في يوم الراحة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='employees.employee', verbose_name='الموظف')),
                ('policy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_summaries', to='attendance.attendancepolicy', verbose_name='السياسة')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_summaries', to='attendance.shift', verbose_name='الشيفت')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'ملخص يومي',
                'verbose_name_plural': 'الملخصات اليومية',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
