# Generated by Django 6.0.7 on 2026-07-25 11:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_dailyattendancesummary'),
        ('companies', '0021_company_payroll_cutoff_day_and_more'),
        ('employees', '0011_employee_instapay_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlexDayAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('date', models.DateField(verbose_name='التاريخ')),
                ('required_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الساعات المطلوبة')),
                ('actual_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الساعات الفعلية')),
                ('delta_hours', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='الفرق (موجب = زيادة، سالب = نقص)')),
                ('adjustment_type', models.CharField(choices=[('overtime', 'ساعات إضافية'), ('shortage', 'نقص ساعات')], max_length=10, verbose_name='النوع')),
                ('status', models.CharField(choices=[('pending', 'قيد مراجعة HR'), ('approved', 'معتمد'), ('rejected', 'مرفوض')], default='pending', max_length=10, verbose_name='الحالة')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ المراجعة')),
                ('review_notes', models.TextField(blank=True, verbose_name='ملاحظات HR')),
                ('attendance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flex_adjustments', to='attendance.attendance', verbose_name='سجل الحضور')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flex_adjustments', to='employees.employee', verbose_name='الموظف')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flex_reviews', to=settings.AUTH_USER_MODEL, verbose_name='تمت المراجعة بواسطة')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flex_adjustments', to='attendance.shift', verbose_name='الشيفت')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'تسوية شيفت مرن',
                'verbose_name_plural': 'تسويات الشيفت المرن',
                'ordering': ['-date'],
                'unique_together': {('employee', 'date', 'status')},
            },
        ),
    ]
