# Generated by Django 6.0.7 on 2026-07-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_flex_day_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionledger',
            name='auto_checkout_grace_minutes',
            field=models.IntegerField(default=30, help_text='عدد الدقائق اللي البرنامج هيستنى فيها بعد خروج الموظف من المنطقة قبل ما يسجل انصراف تلقائي', verbose_name='دقائق الانتظار قبل الانصراف التلقائي'),
        ),
    ]
