# Generated by Django 6.0.7 on 2026-07-25 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_add_auto_checkout_grace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissionledger',
            name='auto_checkout_grace_minutes',
        ),
        migrations.AddField(
            model_name='dailyattendancesummary',
            name='early_leave_minutes',
            field=models.IntegerField(default=0, verbose_name='دقائق الانصراف المبكر'),
        ),
        migrations.AddField(
            model_name='dailyattendancesummary',
            name='flex_delta_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='فرق ساعات الشيفت المرن'),
        ),
        migrations.AddField(
            model_name='dailyattendancesummary',
            name='flex_status',
            field=models.CharField(blank=True, default='', help_text='pending / approved / rejected / none', max_length=10, verbose_name='حالة تسوية الشيفت المرن'),
        ),
        migrations.AddField(
            model_name='dailyattendancesummary',
            name='permission_hours_used',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='ساعات الإذن المستخدمة'),
        ),
    ]
