# Generated by Django 6.0.7 on 2026-07-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0026_daily_summary_new_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='on_mission',
            field=models.BooleanField(default=False, verbose_name='في مأمورية'),
        ),
    ]
