# Generated by Django 6.0.7 on 2026-07-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0027_attendance_on_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='on_mission',
            field=models.BooleanField(default=False, verbose_name='في مأمورية'),
        ),
    ]
