# Generated by Django 6.0.7 on 2026-07-26 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0028_attendancesession_on_mission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinaryaction',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد'),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_disciplinary_actions', to=settings.AUTH_USER_MODEL, verbose_name='وافق بواسطة'),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='payroll_applied',
            field=models.BooleanField(default=False, verbose_name='تم تطبيقه على المرتب'),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='payroll_month',
            field=models.CharField(blank=True, help_text='YYYY-MM', max_length=7, verbose_name='شهر المرتب'),
        ),
        migrations.AddField(
            model_name='disciplinaryaction',
            name='status',
            field=models.CharField(choices=[('pending', 'معلق'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('cancelled', 'ملغي')], default='pending', max_length=20, verbose_name='الحالة'),
        ),
        migrations.CreateModel(
            name='DisciplinaryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('late_repeat', 'تكرار التأخير'), ('absence_repeat', 'تكرار الغياب'), ('early_leave_repeat', 'تكرار الانصراف المبكر'), ('policy_violation', 'مخالفة لائحة'), ('misconduct', 'سوء سلوك'), ('negligence', 'إهمال'), ('other', 'أخرى')], default='policy_violation', max_length=30, verbose_name='نوع المخالفة')),
                ('occurrence_from', models.IntegerField(default=1, verbose_name='من المرة')),
                ('occurrence_to', models.IntegerField(default=1, verbose_name='إلى المرة')),
                ('penalty_type', models.CharField(choices=[('verbal_warning', 'إنذار شفهي'), ('written_warning', 'إنذار كتابي'), ('deduction_days', 'خصم أيام'), ('deduction_amount', 'خصم مبلغ'), ('suspension', 'إيقاف عن العمل')], default='verbal_warning', max_length=30, verbose_name='نوع الجزاء')),
                ('deduction_days', models.DecimalField(decimal_places=2, default=0, help_text='0.25=ربع يوم / 0.5=نص يوم / 1=يوم كامل', max_digits=5, verbose_name='أيام الخصم')),
                ('deduction_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='مبلغ الخصم الثابت')),
                ('description', models.TextField(blank=True, verbose_name='وصف القاعدة')),
                ('display_order', models.IntegerField(default=0)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinary_rules', to='attendance.attendancepolicy', verbose_name='السياسة')),
            ],
            options={
                'verbose_name': 'قاعدة جزاء تأديبي',
                'verbose_name_plural': 'قواعد الجزاءات التأديبية',
                'ordering': ['violation_type', 'occurrence_from'],
            },
        ),
    ]
