# Generated by Django 6.0.7 on 2026-07-28 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0029_add_disciplinary_rule_and_action_fields'),
        ('companies', '0022_companypolicy_tracking_interval_field_visit_minutes_and_more'),
        ('employees', '0013_importlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeWorkLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الموقع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
                ('location_type', models.CharField(choices=[('project', 'موقع مشروع'), ('client', 'موقع عميل'), ('warehouse', 'مخزن'), ('office', 'مكتب فرعي'), ('factory', 'مصنع'), ('site', 'موقع بناء'), ('remote', 'عمل عن بعد'), ('other', 'أخرى')], default='project', max_length=20, verbose_name='نوع الموقع')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط العرض')),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط الطول')),
                ('radius', models.PositiveIntegerField(default=500, help_text='المسافة المسموحة حول الموقع للبصمة', verbose_name='نصف قطر السماح (متر)')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='المدينة')),
                ('country', models.CharField(default='EG', max_length=10, verbose_name='الدولة')),
                ('project_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='كود المشروع')),
                ('client_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='اسم العميل')),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True, verbose_name='الشخص المسئول')),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم التواصل')),
                ('is_shared', models.BooleanField(default=False, help_text='متاح لكل موظفين الشركة/الفرع/القسم', verbose_name='موقع مشترك')),
                ('requires_checkin_photo', models.BooleanField(default=False, verbose_name='يطلب صورة عند الحضور')),
                ('allow_checkout_only', models.BooleanField(default=False, verbose_name='مسموح الانصراف فقط')),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='صالح من تاريخ')),
                ('valid_until', models.DateField(blank=True, help_text='للمشاريع المؤقتة', null=True, verbose_name='صالح حتى تاريخ')),
                ('working_days', models.JSONField(blank=True, default=dict, help_text='مثال: {"sun": true, "mon": true, ...}', verbose_name='أيام العمل')),
                ('working_hours_start', models.TimeField(blank=True, null=True, verbose_name='بداية العمل')),
                ('working_hours_end', models.TimeField(blank=True, null=True, verbose_name='نهاية العمل')),
                ('status', models.CharField(choices=[('pending', 'قيد الموافقة'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('expired', 'منتهي'), ('suspended', 'موقف مؤقتاً')], default='pending', max_length=20, verbose_name='الحالة')),
                ('proposed_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الاقتراح')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الاعتماد')),
                ('rejection_reason', models.TextField(blank=True, null=True, verbose_name='سبب الرفض')),
                ('approval_notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات الاعتماد')),
                ('total_visits_count', models.PositiveIntegerField(default=0, verbose_name='إجمالي الزيارات')),
                ('last_visited_at', models.DateTimeField(blank=True, null=True, verbose_name='آخر زيارة')),
                ('average_visit_duration', models.PositiveIntegerField(default=0, verbose_name='متوسط مدة الزيارة (دقائق)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفعل')),
                ('suspended_reason', models.TextField(blank=True, null=True, verbose_name='سبب الإيقاف')),
                ('priority', models.PositiveIntegerField(default=0, help_text='الأعلى رقم = الأعلى أولوية', verbose_name='الأولوية')),
                ('color_code', models.CharField(default='#3498db', help_text='مثال: #FF5733', max_length=7, verbose_name='لون التمييز')),
                ('icon', models.CharField(default='location', max_length=50, verbose_name='الأيقونة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('tags', models.JSONField(blank=True, default=list, help_text='مثال: ["remote", "high-priority"]', verbose_name='Tags')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='work_locations/photos/', verbose_name='صورة الموقع')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='بيانات إضافية')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_work_locations', to=settings.AUTH_USER_MODEL, verbose_name='معتمد بواسطة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(blank=True, help_text='فارغ لو الموقع مشترك بين موظفين', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_locations', to='employees.employee', verbose_name='الموظف')),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_work_locations', to=settings.AUTH_USER_MODEL, verbose_name='مقترح بواسطة')),
                ('shared_with_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_work_locations', to='companies.branch', verbose_name='مشترك مع فرع')),
                ('shared_with_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_work_locations', to='companies.department', verbose_name='مشترك مع قسم')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'موقع عمل',
                'verbose_name_plural': 'مواقع العمل',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['company', 'employee', 'status'], name='attendance__company_8a731a_idx'), models.Index(fields=['company', 'status', 'is_active'], name='attendance__company_3b47a3_idx')],
            },
        ),
    ]
