# Generated by Django 6.0.7 on 2026-07-28 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0030_employeeworklocation'),
        ('companies', '0022_companypolicy_tracking_interval_field_visit_minutes_and_more'),
        ('employees', '0015_employee_worker_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('from_latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط عرض البداية')),
                ('from_longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط طول البداية')),
                ('from_location_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='اسم موقع البداية')),
                ('to_latitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط عرض النهاية')),
                ('to_longitude', models.DecimalField(decimal_places=7, max_digits=10, verbose_name='خط طول النهاية')),
                ('to_location_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='اسم موقع النهاية')),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='المسافة (كم)')),
                ('travel_time_minutes', models.PositiveIntegerField(verbose_name='وقت التنقل (دقائق)')),
                ('departed_at', models.DateTimeField(verbose_name='تاريخ ووقت المغادرة')),
                ('arrived_at', models.DateTimeField(verbose_name='تاريخ ووقت الوصول')),
                ('time_period', models.CharField(choices=[('morning', 'صباحاً (6ص-12ظ)'), ('noon', 'ظهراً (12ظ-4ع)'), ('evening', 'مساءً (4ع-8م)'), ('night', 'ليلاً (8م-6ص)')], max_length=20, verbose_name='فترة اليوم')),
                ('day_of_week', models.PositiveSmallIntegerField(verbose_name='يوم الأسبوع (0=الأحد, 6=السبت)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('is_verified', models.BooleanField(default=True, help_text='لو false، مش هتُستخدم في حساب المتوسط', verbose_name='رحلة موثوقة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_history', to='employees.employee', verbose_name='الموظف')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'سجل رحلة',
                'verbose_name_plural': 'سجلات الرحلات',
                'ordering': ['-arrived_at'],
                'indexes': [models.Index(fields=['employee', 'time_period'], name='attendance__employe_819c86_idx'), models.Index(fields=['employee', 'from_latitude', 'from_longitude'], name='attendance__employe_789f34_idx')],
            },
        ),
    ]
