# Generated by Django 6.0.7 on 2026-07-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0031_routehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='field_allowance_type',
            field=models.CharField(choices=[('none', 'بدون بدل انتقالات'), ('fixed', 'بدل ثابت شهري'), ('per_visit', 'بدل بالزيارة')], default='none', max_length=10, verbose_name='نوع بدل الانتقالات'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='fixed_field_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='بدل الانتقالات الثابت الشهري'),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='per_visit_allowance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='بدل الانتقالات بالزيارة'),
        ),
    ]
