# Generated by Django 6.0.7 on 2026-07-29 06:52

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0032_add_field_allowance_to_payroll_settings'),
        ('companies', '0022_companypolicy_tracking_interval_field_visit_minutes_and_more'),
        ('employees', '0016_alter_employee_worker_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollallowance',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='من تاريخ'),
        ),
        migrations.CreateModel(
            name='CompanyAllowancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('allowance_type', models.CharField(choices=[('transport', 'بدل مواصلات'), ('housing', 'بدل سكن'), ('phone', 'بدل هاتف'), ('meal', 'بدل وجبة'), ('performance', 'علاوة أداء'), ('clothing', 'بدل ملابس'), ('risk', 'بدل مخاطر'), ('supervision', 'بدل إشراف'), ('shift_night', 'بدل وردية ليلية'), ('travel', 'بدل سفر'), ('remote_work', 'بدل عمل عن بُعد'), ('childcare', 'بدل رعاية أطفال'), ('education', 'بدل تعليم'), ('medical', 'بدل طبي'), ('social', 'بدل اجتماعي'), ('technical', 'بدل فني'), ('representation', 'بدل تمثيل'), ('nature_of_work', 'بدل طبيعة عمل'), ('overtime_fixed', 'بدل ساعات إضافية ثابت'), ('field', 'بدل انتقالات ميدانية'), ('other', 'أخرى')], max_length=20, verbose_name='نوع البدل')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربي')),
                ('name_en', models.CharField(blank=True, default='', max_length=100, verbose_name='الاسم بالإنجليزي')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('scope', models.CharField(choices=[('company', 'الشركة كلها'), ('branch', 'فرع محدد'), ('department', 'إدارة محددة'), ('employees', 'موظفين محددين')], default='company', max_length=20, verbose_name='نطاق التطبيق')),
                ('is_monthly', models.BooleanField(default=True, verbose_name='شهري')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='لحد تاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowance_policies', to='companies.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowance_policies', to='companies.department', verbose_name='الإدارة')),
                ('specific_employees', models.ManyToManyField(blank=True, related_name='specific_allowance_policies', to='employees.employee', verbose_name='موظفين محددين')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'سياسة بدل عام',
                'verbose_name_plural': 'سياسات البدلات العامة',
                'ordering': ['-created_at'],
            },
        ),
    ]
