# Generated by Django 6.0.7 on 2026-07-29 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0033_add_company_allowance_policy'),
        ('companies', '0022_companypolicy_tracking_interval_field_visit_minutes_and_more'),
        ('employees', '0016_alter_employee_worker_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBonusPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('bonus_type', models.CharField(choices=[('incentive', 'حافز'), ('eid', 'مكافأة عيد'), ('annual', 'مكافأة سنوية'), ('performance', 'مكافأة أداء'), ('profit_share', 'حصة أرباح'), ('attendance_bonus', 'مكافأة انتظام'), ('project_completion', 'مكافأة إتمام مشروع'), ('referral', 'مكافأة ترشيح'), ('loyalty', 'مكافأة ولاء'), ('ramadan', 'مكافأة رمضان'), ('back_to_school', 'مكافأة دخول مدارس'), ('marriage', 'مكافأة زواج'), ('newborn', 'مكافأة مولود جديد'), ('other', 'أخرى')], max_length=30, verbose_name='نوع المكافأة')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربي')),
                ('name_en', models.CharField(blank=True, default='', max_length=100, verbose_name='الاسم بالإنجليزي')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('scope', models.CharField(choices=[('company', 'الشركة كلها'), ('branch', 'فرع محدد'), ('department', 'إدارة محددة'), ('employees', 'موظفين محددين')], default='company', max_length=20, verbose_name='نطاق التطبيق')),
                ('is_monthly', models.BooleanField(default=True, verbose_name='شهري')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='لحد تاريخ')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_policies', to='companies.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_policies', to='companies.department', verbose_name='الإدارة')),
                ('specific_employees', models.ManyToManyField(blank=True, related_name='specific_bonus_policies', to='employees.employee', verbose_name='موظفين محددين')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'سياسة مكافأة عامة',
                'verbose_name_plural': 'سياسات المكافآت العامة',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CompanyDeductionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('deduction_type', models.CharField(choices=[('social_insurance', 'تأمينات اجتماعية'), ('health_insurance', 'تأمين صحي'), ('tax', 'ضريبة دخل'), ('union_fee', 'اشتراك نقابة'), ('savings', 'صندوق ادخار'), ('parking', 'خصم انتظار سيارات'), ('uniform', 'خصم زي رسمي'), ('tools', 'خصم عهد / أدوات'), ('loan_recovery', 'استرداد سلفة'), ('other', 'أخرى')], max_length=30, verbose_name='نوع الخصم')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربي')),
                ('name_en', models.CharField(blank=True, default='', max_length=100, verbose_name='الاسم بالإنجليزي')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ')),
                ('scope', models.CharField(choices=[('company', 'الشركة كلها'), ('branch', 'فرع محدد'), ('department', 'إدارة محددة'), ('employees', 'موظفين محددين')], default='company', max_length=20, verbose_name='نطاق التطبيق')),
                ('is_monthly', models.BooleanField(default=True, verbose_name='شهري')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='لحد تاريخ')),
                ('notes', models.TextField(blank=True, default='', verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deduction_policies', to='companies.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deduction_policies', to='companies.department', verbose_name='الإدارة')),
                ('specific_employees', models.ManyToManyField(blank=True, related_name='specific_deduction_policies', to='employees.employee', verbose_name='موظفين محددين')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'سياسة خصم عام',
                'verbose_name_plural': 'سياسات الخصومات العامة',
                'ordering': ['-created_at'],
            },
        ),
    ]
