# Generated by Django 6.0.7 on 2026-08-07 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0034_add_company_deduction_bonus_policies'),
        ('companies', '0022_companypolicy_tracking_interval_field_visit_minutes_and_more'),
        ('employees', '0016_alter_employee_worker_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrollallowance',
            name='name_en',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='الاسم بالإنجليزي'),
        ),
        migrations.AlterField(
            model_name='payrollbonus',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='السبب'),
        ),
        migrations.AlterField(
            model_name='payrollinstallment',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='payrollpenalty',
            name='reason',
            field=models.TextField(blank=True, default='', verbose_name='السبب'),
        ),
        migrations.CreateModel(
            name='CompanyInsurancePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insurance_type', models.CharField(choices=[('social', 'تأمين اجتماعي'), ('medical', 'تأمين طبي')], max_length=10, verbose_name='نوع التأمين')),
                ('name_ar', models.CharField(max_length=100, verbose_name='الاسم بالعربي')),
                ('name_en', models.CharField(blank=True, default='', max_length=100, verbose_name='الاسم بالإنجليزي')),
                ('company_share_type', models.CharField(choices=[('percent', 'نسبة من المرتب'), ('fixed', 'مبلغ ثابت')], default='percent', max_length=10, verbose_name='نوع حصة الشركة')),
                ('company_share_value', models.DecimalField(decimal_places=2, default=0, help_text='لو نسبة اكتب رقم من 0 لـ 100، لو ثابت اكتب المبلغ', max_digits=10, verbose_name='قيمة حصة الشركة')),
                ('employee_share_type', models.CharField(choices=[('percent', 'نسبة من المرتب'), ('fixed', 'مبلغ ثابت')], default='percent', max_length=10, verbose_name='نوع حصة الموظف')),
                ('employee_share_value', models.DecimalField(decimal_places=2, default=0, help_text='لو نسبة اكتب رقم من 0 لـ 100، لو ثابت اكتب المبلغ', max_digits=10, verbose_name='قيمة حصة الموظف')),
                ('min_insured_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأدنى للمرتب المؤمّن')),
                ('max_insured_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الحد الأقصى للمرتب المؤمّن')),
                ('scope', models.CharField(choices=[('company', 'الشركة كلها'), ('branch', 'فرع محدد'), ('department', 'إدارة محددة'), ('employees', 'موظفين محددين')], default='company', max_length=20, verbose_name='نطاق التطبيق')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='لحد تاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='companies.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='insurance_policies', to='companies.department', verbose_name='الإدارة')),
                ('specific_employees', models.ManyToManyField(blank=True, related_name='specific_insurance_policies', to='employees.employee', verbose_name='موظفين محددين')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'سياسة تأمين',
                'verbose_name_plural': 'سياسات التأمين',
                'ordering': ['-created_at'],
            },
        ),
    ]
