# Generated by Django 6.0.7 on 2026-08-07 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0035_add_company_insurance_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinsurancepolicy',
            name='change_reason',
            field=models.TextField(blank=True, default='', help_text='مثال: قرار وزاري رقم 12/2026 - تعديل نسبة التأمين', verbose_name='سبب التغيير'),
        ),
        migrations.AddField(
            model_name='companyinsurancepolicy',
            name='is_superseded',
            field=models.BooleanField(default=False, verbose_name='تم استبدالها بنسخة أحدث'),
        ),
        migrations.AddField(
            model_name='companyinsurancepolicy',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='attendance.companyinsurancepolicy', verbose_name='النسخة السابقة'),
        ),
        migrations.AddField(
            model_name='companyinsurancepolicy',
            name='version_number',
            field=models.PositiveIntegerField(default=1, verbose_name='رقم النسخة'),
        ),
    ]
