# Generated by Django 6.0.7 on 2026-08-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0036_add_insurance_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinsurancepolicy',
            name='calculation_base',
            field=models.CharField(choices=[('basic', 'الراتب الأساسي فقط'), ('gross', 'الراتب الإجمالي (أساسي + بدلات)'), ('employee_custom', 'المرتب التأميني الخاص بالموظف')], default='basic', help_text='على أي مبلغ يُحسب التأمين؟', max_length=20, verbose_name='أساس حساب التأمين'),
        ),
    ]
