# Generated by Django 6.0.7 on 2026-08-07 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0037_add_calculation_base'),
        ('companies', '0022_companypolicy_tracking_interval_field_visit_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPayrollCyclePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cycle_type', models.CharField(choices=[('calendar_month', 'شهر ميلادي (1 → آخر يوم)'), ('custom_month', 'شهر مخصص (تحديد يوم بداية ونهاية)'), ('weekly', 'أسبوعي'), ('bi_weekly', 'كل أسبوعين')], default='calendar_month', max_length=20, verbose_name='نوع الدورة')),
                ('cutoff_day', models.PositiveSmallIntegerField(default=25, help_text='من 1 لـ 31', verbose_name='يوم قفل الشهر')),
                ('pay_day', models.PositiveSmallIntegerField(default=5, help_text='من 1 لـ 31', verbose_name='يوم صرف المرتبات')),
                ('weekly_pay_day', models.CharField(choices=[('sunday', 'الأحد'), ('monday', 'الاثنين'), ('tuesday', 'الثلاثاء'), ('wednesday', 'الأربعاء'), ('thursday', 'الخميس'), ('friday', 'الجمعة'), ('saturday', 'السبت')], default='sunday', max_length=10, verbose_name='يوم الصرف الأسبوعي')),
                ('holiday_handling', models.CharField(choices=[('before', 'الصرف اليوم اللي قبله'), ('after', 'الصرف اليوم اللي بعده'), ('same', 'الصرف نفس اليوم (لو ينفع)')], default='before', max_length=10, verbose_name='معالجة عطلات الصرف')),
                ('default_currency', models.CharField(choices=[('EGP', 'جنيه مصري'), ('USD', 'دولار أمريكي'), ('EUR', 'يورو'), ('SAR', 'ريال سعودي'), ('AED', 'درهم إماراتي')], default='EGP', max_length=5, verbose_name='العملة الافتراضية')),
                ('proration_method', models.CharField(choices=[('30_days', '30 يوم دائماً'), ('actual_days', 'أيام الشهر الفعلية'), ('working_days', 'أيام العمل فقط')], default='30_days', max_length=20, verbose_name='طريقة حساب النسبة والتناسب')),
                ('working_days_per_month', models.PositiveSmallIntegerField(default=22, help_text='يُستخدم لو طريقة الحساب = أيام العمل', verbose_name='أيام العمل الشهرية')),
                ('new_employee_handling', models.CharField(choices=[('full', 'مرتب كامل من أول يوم'), ('prorated', 'بالنسبة والتناسب'), ('next_cycle', 'يبدأ من الدورة الجاية')], default='prorated', max_length=20, verbose_name='معالجة الموظف الجديد')),
                ('payslip_notify_days_before', models.PositiveSmallIntegerField(default=2, verbose_name='إشعار قبل الصرف بكام يوم')),
                ('auto_generate_payroll', models.BooleanField(default=True, verbose_name='توليد Payroll تلقائي')),
                ('payroll_ref_prefix', models.CharField(default='PR', help_text='مثال: PR → PR-2026-08', max_length=10, verbose_name='بادئة الرقم المسلسل')),
                ('approval_level', models.CharField(choices=[('hr_only', 'HR فقط'), ('hr_plus_manager', 'HR + المدير العام'), ('hr_plus_finance_plus_ceo', 'HR + مالي + مدير عام')], default='hr_only', max_length=30, verbose_name='مستوى الموافقة')),
                ('require_approval_before_pay', models.BooleanField(default=True, verbose_name='الموافقة مطلوبة قبل الصرف')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='رقم النسخة')),
                ('change_reason', models.TextField(blank=True, default='', verbose_name='سبب التغيير')),
                ('is_superseded', models.BooleanField(default=False, verbose_name='تم استبدالها بنسخة أحدث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='لحد تاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='attendance.companypayrollcyclepolicy', verbose_name='النسخة السابقة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'سياسة دورة الرواتب',
                'verbose_name_plural': 'سياسات دورة الرواتب',
                'ordering': ['-created_at'],
            },
        ),
    ]
