# Generated by Django 6.0.7 on 2026-08-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0038_add_payroll_cycle_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypayrollcyclepolicy',
            name='first_approver_role',
            field=models.CharField(blank=True, default='hr_manager', help_text='مثال: hr_manager - أي موظف بهذا الدور يقدر يعتمد', max_length=100, verbose_name='الموافق الأول (الدور)'),
        ),
        migrations.AddField(
            model_name='companypayrollcyclepolicy',
            name='second_approver_role',
            field=models.CharField(blank=True, default='', help_text='يظهر لو مستوى الموافقة "HR + المدير"', max_length=100, verbose_name='الموافق الثاني (الدور)'),
        ),
        migrations.AddField(
            model_name='companypayrollcyclepolicy',
            name='third_approver_role',
            field=models.CharField(blank=True, default='', help_text='يظهر لو مستوى الموافقة "HR + مالي + مدير عام"', max_length=100, verbose_name='الموافق الثالث (الدور)'),
        ),
    ]
