# Generated by Django 6.0.7 on 2026-08-07 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0039_add_approver_roles'),
        ('companies', '0022_companypolicy_tracking_interval_field_visit_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyDeductionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='قواعد الحسم الافتراضية', max_length=100, verbose_name='اسم القاعدة')),
                ('late_deduction_per_minute', models.DecimalField(decimal_places=2, default=0, help_text='المبلغ المخصوم من الراتب عن كل دقيقة تأخير', max_digits=10, verbose_name='حسم التأخير لكل دقيقة')),
                ('late_grace_minutes', models.PositiveSmallIntegerField(default=0, help_text='الدقائق الأولى من التأخير لا تُحسب', verbose_name='فترة السماح بالدقائق')),
                ('late_max_per_day', models.DecimalField(decimal_places=2, default=0, help_text='صفر = بدون حد', max_digits=10, verbose_name='الحد الأقصى لحسم التأخير في اليوم')),
                ('absence_deduction_per_day', models.DecimalField(decimal_places=2, default=0, help_text='المبلغ المخصوم عن كل يوم غياب', max_digits=10, verbose_name='حسم الغياب لكل يوم')),
                ('unauthorized_absence_multiplier', models.DecimalField(decimal_places=2, default=1.0, help_text='مضاعف لو الغياب بدون إذن مسبق (مثال: 2 = خصم مضاعف)', max_digits=5, verbose_name='معامل الغياب بدون إذن')),
                ('early_leave_per_minute', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='حسم الخروج المبكر لكل دقيقة')),
                ('early_leave_grace_minutes', models.PositiveSmallIntegerField(default=0, verbose_name='فترة السماح للخروج المبكر')),
                ('scope', models.CharField(choices=[('company', 'الشركة كلها'), ('branch', 'فرع محدد'), ('department', 'إدارة محددة')], default='company', max_length=20, verbose_name='نطاق التطبيق')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='رقم النسخة')),
                ('change_reason', models.TextField(blank=True, default='', verbose_name='سبب التغيير')),
                ('is_superseded', models.BooleanField(default=False, verbose_name='تم استبدالها بنسخة أحدث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='لحد تاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deduction_rules', to='companies.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deduction_rules', to='companies.department', verbose_name='الإدارة')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='attendance.companydeductionrule', verbose_name='النسخة السابقة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'قاعدة حسم',
                'verbose_name_plural': 'قواعد الحسم',
                'ordering': ['-created_at'],
            },
        ),
    ]
