# Generated by Django 6.0.7 on 2026-08-07 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0040_add_deduction_rule'),
        ('companies', '0022_companypolicy_tracking_interval_field_visit_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyBonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='قواعد المكافآت الافتراضية', max_length=100, verbose_name='اسم القاعدة')),
                ('overtime_rate_per_hour', models.DecimalField(decimal_places=2, default=0, help_text='المبلغ الإضافي لكل ساعة عمل بعد الشيفت', max_digits=10, verbose_name='قيمة ساعة الأوفرتايم (EGP)')),
                ('overtime_multiplier_regular', models.DecimalField(decimal_places=2, default=1.5, help_text='مثال: 1.5 = ساعة ونص أجر', max_digits=5, verbose_name='معامل الأوفرتايم العادي')),
                ('overtime_multiplier_weekend', models.DecimalField(decimal_places=2, default=2.0, max_digits=5, verbose_name='معامل الأوفرتايم في الويكند')),
                ('overtime_multiplier_holiday', models.DecimalField(decimal_places=2, default=2.5, max_digits=5, verbose_name='معامل الأوفرتايم في الأعياد الرسمية')),
                ('overtime_max_hours_per_day', models.PositiveSmallIntegerField(default=4, help_text='صفر = بدون حد', verbose_name='الحد الأقصى لساعات الأوفرتايم في اليوم')),
                ('overtime_max_hours_per_month', models.PositiveSmallIntegerField(default=60, help_text='صفر = بدون حد', verbose_name='الحد الأقصى لساعات الأوفرتايم في الشهر')),
                ('overtime_requires_approval', models.BooleanField(default=True, verbose_name='الأوفرتايم يحتاج موافقة مسبقة')),
                ('night_shift_bonus_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل الشيفت الليلي لكل ساعة')),
                ('night_shift_start_hour', models.PositiveSmallIntegerField(default=22, help_text='0-23 (مثال: 22 = 10 مساءً)', verbose_name='ساعة بداية الشيفت الليلي')),
                ('night_shift_end_hour', models.PositiveSmallIntegerField(default=6, help_text='0-23 (مثال: 6 = 6 صباحاً)', verbose_name='ساعة نهاية الشيفت الليلي')),
                ('weekend_bonus_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل العمل في يوم العطلة الأسبوعية')),
                ('holiday_bonus_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل العمل في العيد الرسمي')),
                ('scope', models.CharField(choices=[('company', 'الشركة كلها'), ('branch', 'فرع محدد'), ('department', 'إدارة محددة')], default='company', max_length=20, verbose_name='نطاق التطبيق')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='رقم النسخة')),
                ('change_reason', models.TextField(blank=True, default='', verbose_name='سبب التغيير')),
                ('is_superseded', models.BooleanField(default=False, verbose_name='تم استبدالها بنسخة أحدث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='لحد تاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_rules', to='companies.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_rules', to='companies.department', verbose_name='الإدارة')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='attendance.companybonusrule', verbose_name='النسخة السابقة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'قاعدة مكافأة',
                'verbose_name_plural': 'قواعد المكافآت',
                'ordering': ['-created_at'],
            },
        ),
    ]
