# Generated by Django 6.0.7 on 2026-08-07 20:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0041_add_bonus_rule'),
        ('companies', '0022_companypolicy_tracking_interval_field_visit_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAllowanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='قواعد البدلات الافتراضية', max_length=100, verbose_name='اسم القاعدة')),
                ('field_allowance_type', models.CharField(choices=[('none', 'بدون بدل ميداني'), ('fixed', 'مبلغ ثابت شهري'), ('per_visit', 'لكل زيارة'), ('per_km', 'لكل كيلومتر')], default='none', max_length=15, verbose_name='نوع بدل الميدان')),
                ('fixed_field_allowance', models.DecimalField(decimal_places=2, default=0, help_text='لو نوع البدل = ثابت', max_digits=10, verbose_name='بدل الميدان الثابت (شهري)')),
                ('per_visit_allowance', models.DecimalField(decimal_places=2, default=0, help_text='لو نوع البدل = per_visit', max_digits=10, verbose_name='بدل لكل زيارة')),
                ('per_km_allowance', models.DecimalField(decimal_places=2, default=0, help_text='لو نوع البدل = per_km', max_digits=10, verbose_name='بدل لكل كيلومتر')),
                ('meal_allowance_per_day', models.DecimalField(decimal_places=2, default=0, help_text='يُصرف عن كل يوم عمل', max_digits=10, verbose_name='بدل وجبة يومي (EGP)')),
                ('meal_min_work_hours', models.PositiveSmallIntegerField(default=6, verbose_name='الحد الأدنى لساعات العمل لاستحقاق البدل')),
                ('transport_allowance_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل مواصلات يومي (EGP)')),
                ('transport_allowance_type', models.CharField(choices=[('none', 'بدون بدل'), ('per_day', 'لكل يوم عمل'), ('monthly', 'مبلغ شهري ثابت')], default='none', max_length=15, verbose_name='نوع بدل المواصلات')),
                ('monthly_transport', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='بدل المواصلات الشهري')),
                ('scope', models.CharField(choices=[('company', 'الشركة كلها'), ('branch', 'فرع محدد'), ('department', 'إدارة محددة')], default='company', max_length=20, verbose_name='نطاق التطبيق')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='رقم النسخة')),
                ('change_reason', models.TextField(blank=True, default='', verbose_name='سبب التغيير')),
                ('is_superseded', models.BooleanField(default=False, verbose_name='تم استبدالها بنسخة أحدث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='لحد تاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowance_rules', to='companies.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowance_rules', to='companies.department', verbose_name='الإدارة')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='attendance.companyallowancerule', verbose_name='النسخة السابقة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'قاعدة بدل',
                'verbose_name_plural': 'قواعد البدلات',
                'ordering': ['-created_at'],
            },
        ),
    ]
