# Generated by Django 6.0.7 on 2026-08-07 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0042_add_allowance_rule'),
        ('companies', '0022_companypolicy_tracking_interval_field_visit_minutes_and_more'),
        ('employees', '0017_add_insurance_base_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companybonusrule',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='companybonusrule',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companybonusrule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companybonusrule',
            name='department',
        ),
        migrations.RemoveField(
            model_name='companybonusrule',
            name='previous_version',
        ),
        migrations.RemoveField(
            model_name='companybonusrule',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='companydeductionrule',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='companydeductionrule',
            name='company',
        ),
        migrations.RemoveField(
            model_name='companydeductionrule',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='companydeductionrule',
            name='department',
        ),
        migrations.RemoveField(
            model_name='companydeductionrule',
            name='previous_version',
        ),
        migrations.RemoveField(
            model_name='companydeductionrule',
            name='updated_by',
        ),
        migrations.CreateModel(
            name='AllowanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القاعدة')),
                ('allowance_type', models.CharField(choices=[('field_work', 'بدل الميدان'), ('meals', 'بدل الوجبات'), ('transport', 'بدل المواصلات'), ('housing', 'بدل السكن'), ('phone', 'بدل التليفون'), ('clothing', 'بدل الملابس'), ('representation', 'بدل تمثيل'), ('education', 'بدل تعليم'), ('other', 'بدل آخر')], max_length=20, verbose_name='نوع البدل')),
                ('calculation_type', models.CharField(choices=[('fixed_monthly', 'مبلغ شهري ثابت'), ('per_day', 'لكل يوم عمل'), ('per_visit', 'لكل زيارة'), ('per_km', 'لكل كيلومتر'), ('tiered', 'شرائح تصاعدية')], default='fixed_monthly', max_length=20, verbose_name='طريقة الحساب')),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ (لو ثابت أو per_day/per_visit/per_km)')),
                ('tiers', models.JSONField(default=list, verbose_name='الشرائح (لو tiered)')),
                ('min_work_hours_per_day', models.PositiveIntegerField(default=0, verbose_name='أقل ساعات عمل للاستحقاق')),
                ('scope', models.CharField(choices=[('company', 'الشركة كلها'), ('branch', 'فرع محدد'), ('department', 'إدارة محددة'), ('employees', 'موظفين محددين')], default='company', max_length=20, verbose_name='نطاق التطبيق')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='رقم النسخة')),
                ('change_reason', models.TextField(blank=True, default='', verbose_name='سبب التغيير')),
                ('is_superseded', models.BooleanField(default=False, verbose_name='تم استبدالها بنسخة أحدث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='لحد تاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowance_rules_new', to='companies.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allowance_rules_new', to='companies.department', verbose_name='الإدارة')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='attendance.allowancerule', verbose_name='النسخة السابقة')),
                ('specific_employees', models.ManyToManyField(blank=True, related_name='specific_allowance_rules_new', to='employees.employee', verbose_name='موظفين محددين')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'قاعدة بدل',
                'verbose_name_plural': 'قواعد البدلات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BonusRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القاعدة')),
                ('bonus_type', models.CharField(choices=[('overtime', 'الأوفرتايم'), ('night_shift', 'الشيفت الليلي'), ('weekend_work', 'العمل في الويكند'), ('holiday_work', 'العمل في الأعياد الرسمية')], max_length=20, verbose_name='نوع المكافأة')),
                ('tiers', models.JSONField(default=list, verbose_name='الشرائح')),
                ('max_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأقصى في اليوم (ساعات/EGP)')),
                ('max_per_month', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='الحد الأقصى في الشهر (ساعات/EGP)')),
                ('requires_approval', models.BooleanField(default=False, verbose_name='يحتاج موافقة مسبقة')),
                ('scope', models.CharField(choices=[('company', 'الشركة كلها'), ('branch', 'فرع محدد'), ('department', 'إدارة محددة'), ('employees', 'موظفين محددين')], default='company', max_length=20, verbose_name='نطاق التطبيق')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='رقم النسخة')),
                ('change_reason', models.TextField(blank=True, default='', verbose_name='سبب التغيير')),
                ('is_superseded', models.BooleanField(default=False, verbose_name='تم استبدالها بنسخة أحدث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='لحد تاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_rules_new', to='companies.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_rules_new', to='companies.department', verbose_name='الإدارة')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='attendance.bonusrule', verbose_name='النسخة السابقة')),
                ('specific_employees', models.ManyToManyField(blank=True, related_name='specific_bonus_rules_new', to='employees.employee', verbose_name='موظفين محددين')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'قاعدة مكافأة',
                'verbose_name_plural': 'قواعد المكافآت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PenaltyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم القاعدة')),
                ('penalty_type', models.CharField(choices=[('late_arrival', 'تأخير الحضور'), ('absence', 'الغياب'), ('early_leave', 'الخروج المبكر'), ('missing_checkout', 'عدم تسجيل الخروج')], max_length=20, verbose_name='نوع الجزاء')),
                ('grace_amount', models.PositiveIntegerField(default=0, help_text='بالدقائق لو تأخير/خروج مبكر، بالأيام لو غياب', verbose_name='فترة السماح')),
                ('tiers', models.JSONField(default=list, help_text='قائمة الشرائح من الأقل للأعلى', verbose_name='الشرائح التصاعدية')),
                ('warnings_enabled', models.BooleanField(default=False, verbose_name='تفعيل الإنذارات التصاعدية')),
                ('first_warning_after', models.PositiveIntegerField(default=3, verbose_name='الإنذار الأول بعد كام مرة')),
                ('second_warning_after', models.PositiveIntegerField(default=5, verbose_name='الإنذار الثاني بعد كام مرة')),
                ('termination_after', models.PositiveIntegerField(default=10, verbose_name='الفصل بعد كام مرة')),
                ('scope', models.CharField(choices=[('company', 'الشركة كلها'), ('branch', 'فرع محدد'), ('department', 'إدارة محددة'), ('employees', 'موظفين محددين')], default='company', max_length=20, verbose_name='نطاق التطبيق')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='رقم النسخة')),
                ('change_reason', models.TextField(blank=True, default='', verbose_name='سبب التغيير')),
                ('is_superseded', models.BooleanField(default=False, verbose_name='تم استبدالها بنسخة أحدث')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='لحد تاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty_rules', to='companies.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='penalty_rules', to='companies.department', verbose_name='الإدارة')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='attendance.penaltyrule', verbose_name='النسخة السابقة')),
                ('specific_employees', models.ManyToManyField(blank=True, related_name='specific_penalty_rules', to='employees.employee', verbose_name='موظفين محددين')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'قاعدة جزاء',
                'verbose_name_plural': 'قواعد الجزاءات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='CompanyAllowanceRule',
        ),
        migrations.DeleteModel(
            name='CompanyBonusRule',
        ),
        migrations.DeleteModel(
            name='CompanyDeductionRule',
        ),
    ]
