# Generated by Django 6.0.7 on 2026-08-07 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0043_replace_rules_with_tiers'),
        ('companies', '0022_companypolicy_tracking_interval_field_visit_minutes_and_more'),
        ('employees', '0017_add_insurance_base_salary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='قواعد الإجازات الافتراضية', max_length=100, verbose_name='اسم القاعدة')),
                ('annual_leave_enabled', models.BooleanField(default=True, verbose_name='الإجازة السنوية مفعلة')),
                ('annual_leave_days', models.PositiveSmallIntegerField(default=21, verbose_name='عدد أيام السنوية')),
                ('annual_earn_start', models.CharField(choices=[('immediate', 'من أول يوم'), ('after_probation', 'بعد فترة الاختبار'), ('after_year', 'بعد سنة كاملة')], default='after_probation', max_length=20, verbose_name='متى يبدأ الاستحقاق')),
                ('annual_carry_over', models.BooleanField(default=True, verbose_name='ترحيل الرصيد للسنة التالية')),
                ('annual_max_carry_over', models.PositiveSmallIntegerField(default=7, verbose_name='الحد الأقصى للترحيل')),
                ('annual_cash_out_allowed', models.BooleanField(default=False, verbose_name='صرف نقدي للرصيد المتبقي')),
                ('annual_min_notice_days', models.PositiveSmallIntegerField(default=7, verbose_name='أقل مدة إخطار (أيام)')),
                ('annual_max_consecutive_days', models.PositiveSmallIntegerField(default=30, verbose_name='أقصى إجازة متتالية')),
                ('sick_leave_enabled', models.BooleanField(default=True, verbose_name='الإجازة المرضية مفعلة')),
                ('sick_leave_max_days', models.PositiveSmallIntegerField(default=14, verbose_name='أقصى أيام مرضي في السنة')),
                ('sick_requires_certificate_after', models.PositiveSmallIntegerField(default=3, verbose_name='شهادة طبية بعد كام يوم')),
                ('sick_paid_percentage', models.DecimalField(decimal_places=2, default=75, max_digits=5, verbose_name='نسبة الأجر المدفوعة (%)')),
                ('emergency_leave_enabled', models.BooleanField(default=True, verbose_name='الإجازة الطارئة مفعلة')),
                ('emergency_max_days', models.PositiveSmallIntegerField(default=3, verbose_name='أقصى أيام في السنة')),
                ('emergency_max_per_month', models.PositiveSmallIntegerField(default=1, verbose_name='أقصى مرات في الشهر')),
                ('emergency_min_notice_hours', models.PositiveSmallIntegerField(default=2, verbose_name='أقل ساعات إخطار مسبق')),
                ('emergency_requires_reason', models.BooleanField(default=True, verbose_name='السبب مطلوب')),
                ('emergency_deducted_from_annual', models.BooleanField(default=False, verbose_name='تُخصم من رصيد السنوية')),
                ('maternity_enabled', models.BooleanField(default=True, verbose_name='إجازة الأمومة مفعلة')),
                ('maternity_days', models.PositiveSmallIntegerField(default=90, verbose_name='عدد الأيام')),
                ('maternity_paid', models.BooleanField(default=True, verbose_name='مدفوعة')),
                ('maternity_paid_percentage', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='نسبة الأجر (%)')),
                ('maternity_extension_days', models.PositiveSmallIntegerField(default=0, verbose_name='أيام تمديد (اختياري)')),
                ('maternity_max_times', models.PositiveSmallIntegerField(default=3, verbose_name='الحد الأقصى (مرات)')),
                ('paternity_enabled', models.BooleanField(default=True, verbose_name='إجازة الأبوة مفعلة')),
                ('paternity_days', models.PositiveSmallIntegerField(default=3, verbose_name='عدد الأيام')),
                ('paternity_paid', models.BooleanField(default=True, verbose_name='مدفوعة')),
                ('unpaid_leave_enabled', models.BooleanField(default=True, verbose_name='الإجازة بدون رصيد مفعلة')),
                ('unpaid_deduction_type', models.CharField(choices=[('full_day', 'يوم كامل من المرتب'), ('basic_only', 'من الأساسي فقط'), ('custom', 'مبلغ مخصص لكل يوم')], default='full_day', max_length=20, verbose_name='طريقة الحسم')),
                ('unpaid_custom_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ المخصص لكل يوم')),
                ('max_unpaid_days_per_year', models.PositiveSmallIntegerField(default=30, verbose_name='أقصى أيام بدون رصيد في السنة')),
                ('unpaid_requires_approval', models.BooleanField(default=True, verbose_name='يحتاج موافقة')),
                ('hajj_enabled', models.BooleanField(default=True, verbose_name='إجازة الحج مفعلة')),
                ('hajj_days', models.PositiveSmallIntegerField(default=21, verbose_name='عدد الأيام')),
                ('hajj_paid', models.BooleanField(default=True, verbose_name='مدفوعة')),
                ('hajj_once_in_lifetime', models.BooleanField(default=True, verbose_name='مرة واحدة طوال الخدمة')),
                ('hajj_min_service_years', models.PositiveSmallIntegerField(default=5, verbose_name='أقل سنوات خدمة للاستحقاق')),
                ('bereavement_enabled', models.BooleanField(default=True, verbose_name='إجازة الوفاة مفعلة')),
                ('bereavement_days_first_degree', models.PositiveSmallIntegerField(default=3, verbose_name='أيام (درجة أولى: أب/أم/زوج/زوجة/ابن)')),
                ('bereavement_days_second_degree', models.PositiveSmallIntegerField(default=1, verbose_name='أيام (درجة ثانية: أخ/جد)')),
                ('marriage_enabled', models.BooleanField(default=True, verbose_name='إجازة الزواج مفعلة')),
                ('marriage_days', models.PositiveSmallIntegerField(default=3, verbose_name='عدد الأيام')),
                ('marriage_once_in_lifetime', models.BooleanField(default=True, verbose_name='مرة واحدة')),
                ('scope', models.CharField(choices=[('company', 'الشركة كلها'), ('branch', 'فرع محدد'), ('department', 'إدارة محددة'), ('employees', 'موظفين محددين')], default='company', max_length=20, verbose_name='نطاق التطبيق')),
                ('version_number', models.PositiveIntegerField(default=1, verbose_name='رقم النسخة')),
                ('change_reason', models.TextField(blank=True, default='', verbose_name='سبب التغيير')),
                ('is_superseded', models.BooleanField(default=False, verbose_name='مستبدلة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='لحد تاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_rules', to='companies.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leave_rules', to='companies.department', verbose_name='الإدارة')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='attendance.leaverule', verbose_name='النسخة السابقة')),
                ('specific_employees', models.ManyToManyField(blank=True, related_name='specific_leave_rules', to='employees.employee', verbose_name='موظفين محددين')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'قاعدة إجازات',
                'verbose_name_plural': 'قواعد الإجازات',
                'ordering': ['-created_at'],
            },
        ),
    ]
