# Generated by Django 6.0.7 on 2026-08-07 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0045_add_manual_entries'),
        ('companies', '0022_companypolicy_tracking_interval_field_visit_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ضريبة الدخل', max_length=100, verbose_name='اسم السياسة')),
                ('country', models.CharField(choices=[('EG', 'مصر'), ('SA', 'السعودية'), ('AE', 'الإمارات'), ('KW', 'الكويت'), ('OTHER', 'أخرى')], default='EG', max_length=10, verbose_name='الدولة')),
                ('tax_year', models.PositiveSmallIntegerField(default=2026, verbose_name='السنة الضريبية')),
                ('tax_brackets', models.JSONField(default=list, help_text='قائمة الشرائح: from/to/rate', verbose_name='الشرائح الضريبية (سنوي)')),
                ('personal_exemption_single', models.DecimalField(decimal_places=2, default=9000, max_digits=10, verbose_name='إعفاء أعزب (سنوي)')),
                ('personal_exemption_married', models.DecimalField(decimal_places=2, default=9000, max_digits=10, verbose_name='إعفاء متزوج (سنوي)')),
                ('child_exemption', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='إعفاء لكل ابن معال (سنوي)')),
                ('max_children_exempted', models.PositiveSmallIntegerField(default=3, verbose_name='أقصى عدد أبناء للإعفاء')),
                ('exempt_social_insurance', models.BooleanField(default=True, verbose_name='إعفاء حصة الموظف من التأمين الاجتماعي')),
                ('exempt_medical_insurance', models.BooleanField(default=True, verbose_name='إعفاء حصة الموظف من التأمين الطبي')),
                ('additional_exemption', models.DecimalField(decimal_places=2, default=0, help_text='مثال: أقساط تأمين حياة أو صناديق ادخار', max_digits=10, verbose_name='إعفاءات إضافية سنوية')),
                ('calculation_method', models.CharField(choices=[('monthly_progressive', 'حساب تقدمي شهري (12/12 من السنوي)'), ('cumulative', 'حساب تراكمي (Cumulative)')], default='monthly_progressive', max_length=20, verbose_name='طريقة الحساب')),
                ('scope', models.CharField(choices=[('company', 'الشركة كلها'), ('branch', 'فرع محدد'), ('department', 'إدارة محددة')], default='company', max_length=20, verbose_name='نطاق التطبيق')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('change_reason', models.TextField(blank=True, default='')),
                ('is_superseded', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='لحد تاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_policies', to='companies.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tax_policies', to='companies.department', verbose_name='الإدارة')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='attendance.taxpolicy', verbose_name='النسخة السابقة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'سياسة ضريبة الدخل',
                'verbose_name_plural': 'سياسات ضريبة الدخل',
                'ordering': ['-created_at'],
            },
        ),
    ]
