# Generated by Django 6.0.7 on 2026-08-07 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0046_add_tax_policy'),
        ('companies', '0022_companypolicy_tracking_interval_field_visit_minutes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EndOfServicePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='مكافأة نهاية الخدمة', max_length=100, verbose_name='اسم السياسة')),
                ('salary_base_type', models.CharField(choices=[('last_basic', 'آخر راتب أساسي'), ('last_gross', 'آخر راتب إجمالي (أساسي + بدلات)'), ('avg_3_months', 'متوسط آخر 3 شهور'), ('avg_6_months', 'متوسط آخر 6 شهور'), ('avg_12_months', 'متوسط آخر 12 شهر')], default='last_basic', max_length=20, verbose_name='أساس الحساب')),
                ('service_tiers', models.JSONField(default=list, help_text='قائمة الشرائح: from_years/to_years/months_per_year', verbose_name='شرائح سنوات الخدمة')),
                ('min_service_months', models.PositiveSmallIntegerField(default=12, help_text='لو الموظف اشتغل أقل من ده مايستحقش', verbose_name='أقل خدمة للاستحقاق (بالشهور)')),
                ('max_months_cap', models.DecimalField(decimal_places=1, default=0, help_text='0 = بدون حد. مثال: 24 = أقصى 24 شهر', max_digits=5, verbose_name='الحد الأقصى للمكافأة (بالشهور)')),
                ('percent_on_resignation', models.DecimalField(decimal_places=2, default=50, help_text='مثال: 50 = نصف المكافأة عند الاستقالة', max_digits=5, verbose_name='نسبة الاستحقاق عند الاستقالة (%)')),
                ('percent_on_termination', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='نسبة الاستحقاق عند إنهاء الخدمة من قبل الشركة (%)')),
                ('percent_on_death', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='نسبة الاستحقاق عند الوفاة (%)')),
                ('percent_on_retirement', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='نسبة الاستحقاق عند بلوغ سن المعاش (%)')),
                ('percent_on_disability', models.DecimalField(decimal_places=2, default=100, max_digits=5, verbose_name='نسبة الاستحقاق عند العجز الكلي (%)')),
                ('percent_on_misconduct', models.DecimalField(decimal_places=2, default=0, help_text='عادة 0% في حالات الفصل التأديبي', max_digits=5, verbose_name='نسبة الاستحقاق عند الفصل بسبب سوء السلوك (%)')),
                ('include_bonuses_in_base', models.BooleanField(default=False, verbose_name='تشمل المكافآت السنوية في الحساب')),
                ('partial_year_calculation', models.CharField(choices=[('proportional', 'بالنسبة والتناسب'), ('rounded_up', 'تُحسب سنة كاملة'), ('rounded_down', 'تُهمل')], default='proportional', max_length=15, verbose_name='معاملة السنة غير المكتملة')),
                ('tax_exempted', models.BooleanField(default=True, verbose_name='معفاة من الضريبة')),
                ('scope', models.CharField(choices=[('company', 'الشركة كلها'), ('branch', 'فرع محدد'), ('department', 'إدارة محددة')], default='company', max_length=20, verbose_name='نطاق التطبيق')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('change_reason', models.TextField(blank=True, default='')),
                ('is_superseded', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('start_date', models.DateField(verbose_name='من تاريخ')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='لحد تاريخ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eos_policies', to='companies.branch', verbose_name='الفرع')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eos_policies', to='companies.department', verbose_name='الإدارة')),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='attendance.endofservicepolicy', verbose_name='النسخة السابقة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'سياسة مكافأة نهاية الخدمة',
                'verbose_name_plural': 'سياسات مكافأة نهاية الخدمة',
                'ordering': ['-created_at'],
            },
        ),
    ]
