# Generated by Django 6.0.7 on 2026-08-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0047_add_eos_policy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeworklocation',
            name='status',
            field=models.CharField(choices=[('pending_manager', 'قيد موافقة المدير'), ('pending_hr', 'قيد اعتماد HR'), ('approved', 'معتمد'), ('rejected', 'مرفوض'), ('expired', 'منتهي'), ('suspended', 'موقف مؤقتاً')], default='pending_manager', max_length=20, verbose_name='الحالة'),
        ),
    ]
