# Generated by Django 6.0.7 on 2026-08-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0048_alter_employeeworklocation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyworkpolicy',
            name='attendance_trigger_mode',
            field=models.CharField(choices=[('manual', 'يدوي فقط'), ('notification', 'إشعار ذكي'), ('auto', 'تسجيل تلقائي')], default='notification', max_length=20, verbose_name='طريقة تسجيل الحضور'),
        ),
        migrations.AddField(
            model_name='companyworkpolicy',
            name='location_loss_action',
            field=models.CharField(choices=[('ignore', 'تجاهل'), ('alert_only', 'تنبيه الإدارة فقط'), ('record_violation', 'تسجيل مخالفة')], default='alert_only', max_length=20, verbose_name='إجراء فقد الموقع'),
        ),
        migrations.AddField(
            model_name='companyworkpolicy',
            name='location_loss_grace_minutes',
            field=models.PositiveIntegerField(default=5, verbose_name='دقائق سماح قبل اعتبار الموقع مفقوداً'),
        ),
        migrations.AddField(
            model_name='companyworkpolicy',
            name='pre_shift_checkin_window',
            field=models.PositiveIntegerField(default=15, verbose_name='السماح بالحضور قبل الشيفت (دقيقة)'),
        ),
        migrations.AddField(
            model_name='companyworkpolicy',
            name='require_live_location',
            field=models.BooleanField(default=True, verbose_name='الموقع مطلوب بعد الحضور'),
        ),
    ]
