# Generated by Django 6.0.7 on 2026-08-11 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0049_companyworkpolicy_attendance_trigger_mode_and_more'),
        ('employees', '0019_departmentjobtitlerule_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeworklocation',
            name='assigned_employees',
            field=models.ManyToManyField(blank=True, related_name='assigned_work_locations', to='employees.employee', verbose_name='الموظفين المخصصين'),
        ),
    ]
