# Generated by Django 6.0.7 on 2026-08-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0050_employeeworklocation_assigned_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancepolicy',
            name='late_warning_deduction_type',
            field=models.CharField(choices=[('fixed', 'ثابت'), ('progressive', 'تصاعدي بحد أقصى'), ('progressive_step', 'تصاعدي كل عدد مرات')], default='fixed', max_length=20, verbose_name='نوع الخصم'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='late_warning_deduction_value',
            field=models.DecimalField(decimal_places=2, default=0.25, max_digits=4, verbose_name='قيمة الخصم الأساسية (جزء من اليوم)'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='late_warning_enabled',
            field=models.BooleanField(default=False, verbose_name='تفعيل نظام الإنذارات'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='late_warning_max_deduction',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='الحد الأقصى للخصم (جزء من اليوم)'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='late_warning_step_rate',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='معدل الزيادة كل N مرات'),
        ),
        migrations.AddField(
            model_name='attendancepolicy',
            name='late_warning_threshold',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='عدد الإنذارات قبل الخصم'),
        ),
        migrations.AddField(
            model_name='lateincident',
            name='deduction_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='قيمة الخصم (جزء من اليوم)'),
        ),
        migrations.AddField(
            model_name='lateincident',
            name='was_deducted',
            field=models.BooleanField(default=False, verbose_name='تم الخصم'),
        ),
    ]
