# Generated by Django 6.1 on 2026-08-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0051_add_late_warning_system'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='early_checkout_allowed',
            field=models.BooleanField(default=False, verbose_name='السماح بالانصراف المبكر'),
        ),
        migrations.AddField(
            model_name='shift',
            name='early_checkout_minutes',
            field=models.IntegerField(default=0, help_text='مثال: 60 = السماح بالانصراف قبل ميعاد الشيفت بساعة', verbose_name='الانصراف المبكر المسموح (دقائق)'),
        ),
        migrations.AddField(
            model_name='shift',
            name='late_checkout_allowed',
            field=models.BooleanField(default=False, verbose_name='السماح بالانصراف المتأخر'),
        ),
        migrations.AddField(
            model_name='shift',
            name='late_checkout_minutes',
            field=models.IntegerField(default=0, help_text='مثال: 180 = السماح بالانصراف بعد ميعاد الشيفت بـ 3 ساعات', verbose_name='الانصراف المتأخر المسموح (دقائق)'),
        ),
    ]
