# Generated by Django 6.0.7 on 2026-08-23 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0052_shift_early_checkout_allowed_and_more'),
        ('companies', '0023_department_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='absencerule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.branch', verbose_name='الفرع المستهدف'),
        ),
        migrations.AddField(
            model_name='absencerule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.department', verbose_name='القسم المستهدف'),
        ),
        migrations.AddField(
            model_name='laterule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.branch', verbose_name='الفرع المستهدف'),
        ),
        migrations.AddField(
            model_name='laterule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.department', verbose_name='القسم المستهدف'),
        ),
        migrations.AddField(
            model_name='overtimerule',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.branch', verbose_name='الفرع المستهدف'),
        ),
        migrations.AddField(
            model_name='overtimerule',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.department', verbose_name='القسم المستهدف'),
        ),
    ]
