# Generated by Django 6.0.7 on 2026-08-27 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0051_shift_early_checkout_allowed_and_more'),
        ('attendance', '0053_absencerule_branch_absencerule_department_and_more'),
    ]

    operations = [
    ]
