# Generated by Django 6.0.7 on 2026-09-03 23:16
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0054_merge_20260828_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='backdated_reason',
            field=models.TextField(blank=True, verbose_name='سبب اختيار تاريخ سابق'),
        ),
        migrations.AddField(
            model_name='mission',
            name='is_backdated',
            field=models.BooleanField(default=False, verbose_name='مهمة بتاريخ سابق'),
        ),
    ]
