# Generated by Django 6.0.7 on 2026-09-05 07:12
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0055_mission_backdated_reason_mission_is_backdated_and_more'),
        ('companies', '0024_workcharter_target_branches_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualEntryApprovalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ آخر تعديل')),
                ('entry_type', models.CharField(choices=[('penalty', 'جزاء'), ('bonus', 'مكافأة'), ('allowance', 'بدل')], max_length=20, verbose_name='نوع الإدخال')),
                ('category', models.CharField(max_length=25, verbose_name='الفئة')),
                ('requires_approval', models.BooleanField(default=True, verbose_name='يحتاج موافقة')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_set', to='companies.company', verbose_name='الشركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ بواسطة')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL, verbose_name='آخر تعديل بواسطة')),
            ],
            options={
                'verbose_name': 'إعداد موافقة الإدخالات اليدوية',
                'verbose_name_plural': 'إعدادات موافقة الإدخالات اليدوية',
                'unique_together': {('company', 'entry_type', 'category')},
            },
        ),
    ]
