# Generated by Django 6.0.7 on 2026-09-06 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0056_shift_early_checkin_grace_shift_early_checkout_grace_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyworkpolicy',
            name='hr_can_cancel_attendance',
            field=models.BooleanField(default=False, help_text='يسمح لمدير الشركة بإلغاء سجلات الحضور', verbose_name='الـ HR يقدر يلغي الحضور'),
        ),
        migrations.AddField(
            model_name='companyworkpolicy',
            name='hr_can_edit_attendance',
            field=models.BooleanField(default=False, help_text='يسمح لمدير الشركة بتعديل سجلات الحضور', verbose_name='الـ HR يقدر يعدل الحضور'),
        ),
    ]
