# Generated by Django 6.0.7 on 2026-09-18 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0057_companyworkpolicy_hr_can_cancel_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='geofence_alert_sent',
            field=models.BooleanField(default=False, verbose_name='تم إرسال تنبيه الخروج'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='last_location_ping',
            field=models.DateTimeField(blank=True, null=True, verbose_name='آخر تحديث للموقع'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='outside_geofence_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ ووقت الخروج عن النطاق'),
        ),
        migrations.AddField(
            model_name='shift',
            name='early_checkin_grace',
            field=models.IntegerField(default=30, verbose_name='سماحية الحضور المبكر (دقائق)'),
        ),
        migrations.AddField(
            model_name='shift',
            name='early_checkout_grace',
            field=models.IntegerField(default=0, verbose_name='سماحية الانصراف المبكر (دقائق)'),
        ),
    ]
